# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Latin year 8
'''
ZHENGLIN_YEAR8 = {
    'title': 'Cambridge Latin Course Book II',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'latin',
    'sections':[
        {
            'title': 'in Britanniā',
            'exercises': [
                ('Britanniā: Britannia', 'Britain'),
                ('dēplōrant: dēplōrāre', 'complain about'),
                ('pluit', 'it is raining'),
                ('sōlem: sōl', 'sun'),
                ('Ītaliam: Ītalia', 'Italy'),
                ('redīre volō', 'I want to return'),
                ('aquam: aqua', 'water'),
                ('bibere nōn possum', 'I cannot drink'),
                ('foeda', 'foul, filthy'),
                ('pavīmentum', 'floor'),
                ('lavat: lavāre', 'wash'),
                ('labōrāre nōlō', 'I do not want to work'),
                ('fessus', 'tired'),
                ('advenit: advenīre', 'arrive'),
                ('apud Canticōs', 'among the Cantici'),
                ('coniūrātiōnem: coniūrātiō', 'plot'),
                ('vulnerātus', 'wounded'),
                ('metallum', 'a mine'),
                ('hospes', 'host'),
                ('quamquam', 'although'),
                ('ferrum', 'iron'),
                ('effodiēbant: effodere', 'dig'),
                ('ad sē', 'to him'),
                ('inūtilis', 'useless'),
                ('carnificibus: carnifex', 'executioner'),
                ('nōmen', 'name'),
                ('vindicāre voluit', 'wanted to avenge'),
                ('itaque', 'and so'),
                ('ubi', 'when'),
                ('cēterī', 'the others, the rest'),
                ('pugiōnem: pugiō', 'dagger'),
                ('custōdēs: custōs', 'guard'),
                ('ēlūsit: ēlūdere', 'slip past'),
                ('manūs ...extendit', 'stretched out his hands'),
                ('veniam petīvit', 'begged for mercy'),
                ('saeviēbat: saevīre', 'be in a rage'),
                ('cōnsciī: cōnscius', 'accomplice'),
                ('supplicium', 'death penalty'),
                ('poscō: poscere', 'demand'),
                ('nocēns', 'guilty'),
                ('innocentēs: innocēns', 'innocent'),
                ('coniūrābant: coniūraāre', 'plot'),
                ('invītus', 'unwilling, relucant'),
                ('in āream', 'into the courtyard'),
                ('in ōrdinēs', 'in rows'),
                ('sē īnstrūxērunt: sē īnstruere', 'draw oneself up'),
                ('per ōrdinēs', 'along the rows'),
                ('sēcum', 'with him'),
                ('rēx', 'king'),
                ('equitēs: eques', 'horseman'),
                ('equō: equus', 'horse'),
                ('puerī puellaeque', 'the boys and girs'),
                ('geminī', 'twins'),
                ('simulac', 'as soon as'),
                ('īnsolēns', 'rude, insolent'),
                ('ērūpit: ērumpere', 'break away'),
                ('nōnnūllī', 'some, several'),
                ('retrāxērunt: retrahere', 'drag back'),
                ('sē recēpit: sē recipere', 'recover'),
                ('illud', 'that'),
                ('pūnīre', 'punish'),
                ('facile', 'easy'),
                ('agrōs: ager', 'field'),
                ('segetem: seges', 'crop, harvest'),
                ('frūmentum', 'grain'),
                ('horreum', 'barn, granary'),
                ('intulērunt: īnferre', 'bring in'),
                ('arātōrēs: arātor', 'ploughman'),
                ('magister', 'foreman'),
                ('nōnne?', 'surely?'),
                ('pareest: pareesse', 'be in charge of'),
                ('eī', 'to him'),
                ('perītissimus: perīrus', 'skillful'),
                ('sōlus', 'alone, only'),
                ('rem rūsticam', 'the farming'),
                ('cūrāre', 'look after, supervise'),
                ('simulatque', 'as soon as'),
                ('hī', 'these'),
                ('ferunt: ferre', 'bring'),
                ('ignāvīs: ignāvus', 'lazy'),
                ('aedificium', 'building'),
                ('dīra', 'dreadful'),
                ('taurus', 'bull'),
                ('animal', 'animal'),
                ('impetum: impetus', 'attack'),
                ('neglegēns', 'careless'),
                ('Britannīs: Britannī', 'Britons'),
                ('adveniō, advenīre, advēnī', 'arrive'),
                ('alter', 'the other, the second'),
                ('cantō, cantāre, cantāvī', 'sing'),
                ('dīcō, dīcere, dīxī', 'say'),
                ('excitō, excitāre, excitāvī', 'arouse, wake up'),
                ('interficiō, interficere, interfēcī', 'kill'),
                ('ita vērō', 'yes'),
                ('nōlō', 'I do not want'),
                ('novus', 'new'),
                ('nūllus', 'not any, no'),
                ('possum', 'I can, I am able'),
                ('ruō, ruere, ruī', 'rush'),
                ('sē', 'himself'),
                ('trahō, trahere, trāxī', 'drag'),
                ('vīta', 'life'),
                ('volō', 'I want'),
                ('vulnerō, vulnerāre, vulnerāvī', 'wound'),
            ]
        }
    ]
}
