# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Latin year 7
'''
ZHENGLIN_YEAR7 = {
    'title': 'Latin Year 7',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'latin',
    'sections':[
        {
            'title': 'Caecilius',
            'exercises': [
                ('canis', 'dog'),
                ('coquus', 'cook'),
                ('est', 'is'),
                ('fīlius', 'son'),
                ('hortus', 'garden'),
                ('in', 'in'),
                ('labōrat', 'works, is working'),
                ('māter', 'mother'),
                ('pater', 'father'),
                ('sedet', 'sits, is sitting'),
                ('servus', 'slave'),
                ('via', 'street'),
                ('in tablīnō', 'in the study'),
                ('in ātriō', 'in the atrium (main room)'),
                ('in triclīniō', 'in the dining-room'),
                ('in hortō', 'in the garden'),
                ('in culīnā', 'in the kitchen'),
                ('in viā', 'in the street'),
                ('scrībit', 'writes, is writing'),
                ('bibit', 'drinks, is drinking'),
                ('dormit', 'sleeps, is sleeping'),
                ('intrat', 'enters'),
                ('circumspectat', 'looks round'),
                ('cibus', 'food'),
                ('in mēnsā', 'on the table'),
                ('salit', 'jumps'),
                ('stat', 'stands'),
                ('stertit', 'snores'),
                ('lātrat', 'barks'),
                ('īrātus', 'angry'),
                ('pestis!', 'pest!'),
                ('furcifer!', 'scoundrel!'),
                ('exit', 'goes out'),
                ('faucēs', 'entrance door'),
                ('ātrium', 'main room'),
                ('cubiculum', 'bedroom'),
                ('tablīnum', 'study'),
                ('peristylium', 'garden court'),
                ('triclīnium', 'dining-room'),
                ('culīna', 'kitchen'),
                ('latrīna', 'lavatory'),
                ('iānua', 'front door'),
                ('impluvium', 'pool for rain water'),
                ('larārium', 'shrine of the household gods')
            ]
        },  # a section object
        {
            'title': 'In Villa',
            'exercises': [
                ('amīcus', 'friend'),
                ('ancilla', 'slave-girl, maid'),
                ('cēna', 'dinner'),
                ('cibus', 'food'),
                ('dominus', 'master'),
                ('dormit', 'sleeps'),
                ('intrat', 'enters'),
                ('laetus', 'happy'),
                ('laudat', 'praises'),
                ('mercātor', 'merchant'),
                ('quoque', 'also'),
                ('salūtat', 'greets'),
                ('vīsitat', 'visits, is visting'),
                ('vīllam', 'house'),
                ('pecūniam numerat', 'is counting money'),
                ('argentārius', 'banker'),
                ('respondet', 'replies'),
                ('in lectō recumbit', 'reclines on a couch'),
                ('cantat', 'is singing'),
                ('pāvōnem', 'peacock'),
                ('audit', 'hears'),
                ('nōn est', 'is not'),
                ('cēnam', 'dinner'),
                ('exspectat', 'is waiting for'),
                ('vituperat', 'blames, curses'),
                ('portat', 'is carring'),
                ('vīnum', 'wine'),
                ('gustat', 'tastes'),
                ('optimus', 'very good, excellent'),
                ('suāviter', 'sweetly'),
                ('dēlectat', 'pleases'),
                ('mox', 'soon'),
                ('et', 'and'),
                ('videt', 'sees'),
                ('cibum cōnsūmit', 'eats the food'),
                ('magnificē', 'magnificently, in style'),
                ('cēnat', 'dines, has dinner'),
                ('spectat', 'looks at'),
                ('laetissimus', 'very happy')
            ]
        }, # a section object
        {
            'title': 'Negotium',
            'exercises': [
                ('ad', 'to'),
                ('bibit', 'drinks'),
                ('circumspectat', 'looks around'),
                ('clāmat', 'shouts'),
                ('ecce!', 'look!'),
                ('et', 'and'),
                ('exit', 'goes out'),
                ('exspectat', 'waits for'),
                ('iānua', 'door'),
                ('īrātus', 'angry'),
                ('leō', 'lion'),
                ('magnus', 'big'),
                ('nāvis', 'ship'),
                ('nōn', 'not'),
                ('portat', 'carries'),
                ('respondet', 'replies'),
                ('rīdet', 'laughs, smiles'),
                ('salvē!', 'hello!'),
                ('surgit', 'gets up, stands up'),
                ('taberna', 'shop, inn'),
                ('videt', 'sees'),
                ('vīnum', 'wine'),
                ('in forō', 'in the forum'),
                ('negōtium agit', 'is working, is doing business'),
                ('pictor', 'painter, artist'),
                ('tōnsor', 'barber'),
                ('vēnālīcius', 'slave-dealer'),
                ('nōn venit', 'does not come'),
                ('ad vīllam', 'to the house'),
                ('iānuam pulsat', 'knocks at the door'),
                ('ad iānuam', 'to the door'),
                ('aperit', 'opens'),
                ('vocat', 'calls'),
                ('dūcit', 'leads, takes'),
                ('pictūram pingit', 'paints a picture'),
                ('fūstem', 'club'),
                ('tenet', 'holds, is holding'),
                ('verberat', 'strikes, is striking'),
                ('revenit', 'returns'),
                ('in tabernā', 'in the shop'),
                ('occupātus', 'busy'),
                ('in sellā', 'in the chair'),
                ('novāculam', 'razor'),
                ('barbam tondet', 'is trimming his beard'),
                ('poēta', 'poet'),
                ('versum recitat', 'recites a line, recites a verse'),
                ('scurrīlis', 'rude'),
                ('secat', 'cuts'),
                ('fluit', 'flows'),
                ('ē tabernā', 'out of the shop'),
                ('ad portum', 'to the harbour'),
                ('nāvem Syriam', 'Syrian ship'),
                ('prope nāvem', 'near the ship'),
                ('contentus', 'satisfied'),
                ('pulchra', 'beautiful'),
                ('linguam Latīnam', 'Latin language'),
                ('discit', 'is learning'),
                ('docta', 'skillful, educated'),
                ('satis', 'enough'),
            ]
        }, # a section object
        {
            'title': 'In Foro',
            'exercises': [
                ('agit', 'does'),
                ('ānulus', 'ring'),
                ('coquit', 'cooks'),
                ('cūr?', 'why?'),
                ('ē', 'from, out of'),
                ('ego', 'I'),
                ('ēheu!', 'oh dear!, oh no!'),
                ('habet', 'has'),
                ('inquit', 'says'),
                ('iūdex', 'judge'),
                ('mendāx', 'liar'),
                ('pecūnia', 'money'),
                ('perterritus', 'terrified'),
                ('poēta', 'poet'),
                ('quaerit', 'looks for, searches for'),
                ('quis?', 'who?'),
                ('reddit', 'gives back'),
                ('satis', 'enough'),
                ('sed', 'but'),
                ('signum', 'sign, seal'),
                ('tū', 'you'),
                ('vocat', 'calls')
            ]
        },  # a section object
        {
            'title': 'to be',
            'exercises': [
                ('sum', 'I am'),
                ('es', 'you (sing.) are'),
                ('est', 'he/she/it is'),
                ('summus', 'we are'),
                ('estis', 'you (pl.) are'),
                ('sunt', 'they are'),
                ('eram', 'I was'),
                ('eras', 'you (sing.) were'),
                ('erat', 'he/she/it was'),
                ('eramus', 'we were'),
                ('eratis', 'you (pl.) were'),
                ('erant', 'they were'),
            ]
        }, # a section object
        {
            'title': 'In Theatro',
            'exercises': [
                ('adest', 'is here'),
                ('adsunt', 'are here'),
                ('agricola', 'farmer'),
                ('ambulat', 'walks'),
                ('audit', 'hears'),
                ('clāmor', 'shout, uproar'),
                ('contendit', 'hurries'),
                ('fābula', 'play, story'),
                ('fēmina', 'woman'),
                ('hodiē', 'today'),
                ('iuvenis', 'young man'),
                ('meus', 'my mine'),
                ('multus', 'much'),
                ('multī', 'many'),
                ('optimus', 'very good, excellent'),
                ('petit', 'makes for, attacks'),
                ('plaudit', 'applauds'),
                ('puella', 'girl'),
                ('senex', 'old man'),
                ('spectat', 'looks at, watches'),
                ('stat', 'stands'),
                ('turba', 'crowd'),
                ('ubi?', 'where?'),
                ('urbs', 'city'),
                ('venit', 'comes'),
            ]
        }, # a section object
        {
            'title': 'Felix',
            'exercises': [
                ('abest', 'is out, is absent'),
                ('aberat', 'was out, was absent'),
                ('cubiculum', 'bedroom'),
                ('emit', 'buys'),
                ('ferōciter', 'fiercely'),
                ('festīnat', 'hurries'),
                ('fortis', 'brave'),
                ('fūr', 'thief'),
                ('intentē', 'intently, carefully'),
                ('lībertus', 'freedman, ex-slace'),
                ('ōlim', 'once, some time ago'),
                ('parvus', 'small'),
                ('per', 'through'),
                ('postquam', 'after'),
                ('pulsat', 'hits, thumps'),
                ('quod', 'because'),
                ('rēs', 'thing'),
                ('scrībit', 'writes'),
                ('subitō', 'suddenly'),
                ('superat', 'overcomes, overpowers'),
                ('tum', 'then'),
                ('tuus', 'yours'),
                ('vēndit', 'sells'),
                ('vituperat', 'blames, curses'),
            ]
        }, # a section object
        {
            'title': 'Cena',
            'exercises': [
                ('cēnat', 'dines'),
                ('cōnspicit', 'catches sight of'),
                ('cum', 'with'),
                ('facit', 'makes, does'),
                ('heri', 'yesterday'),
                ('ingēns', 'huge'),
                ('intellegit', 'understands'),
                ('lacrimat', 'weeps, cries'),
                ('mortuus', 'dead'),
                ('nārrat', 'tells, relates'),
                ('necat', 'kills'),
                ('nihil', 'nothing'),
                ('omnis', 'all'),
                ('parat', 'prepares'),
                ('prope', 'near'),
                ('rogat', 'asks'),
                ('tacitē', 'quitely'),
                ('tamen', 'however'),
                ('terret', 'frightens'),
                ('valdē', 'very much'),
            ]
        }, # a section object
        {
            'title': 'Gladiatores',
            'exercises': [
                ('agitat', 'chases, hunts'),
                ('cōnsūmit', 'eats'),
                ('dūcit', 'leads, takes'),
                ('eum', 'him'),
                ('facile', 'easily'),
                ('ferōx', 'fierce'),
                ('gladius', 'sword'),
                ('hic', 'this'),
                ('ignāvus', 'cowardly'),
                ('nūntius', 'messenger'),
                ('pēs', 'foot'),
                ('porta', 'gate'),
                ('postulat', 'demands'),
                ('puer', 'boy'),
                ('pugnat', 'fights'),
                ('saepe', 'often'),
                ('sanguis', 'blood'),
                ('silva', 'wood'),
                ('spectāculum', 'show, spectacle'),
                ('statim', 'at once'),
                ('tōtus', 'whole'),
            ]
        }, # a section object
    ]
}
