# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Latin year 7
'''
ZHENGLIN_YEAR7 = {
    'title': 'Cambridge Latin Course Book I',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'latin',
    'sections':[
        {
            'title': 'Caecilius',
            'exercises': [
                ('canis', 'dog'),
                ('coquus', 'cook'),
                ('est', 'is'),
                ('fīlius', 'son'),
                ('hortus', 'garden'),
                ('in', 'in'),
                ('labōrat', 'works, is working'),
                ('māter', 'mother'),
                ('pater', 'father'),
                ('sedet', 'sits, is sitting'),
                ('servus', 'slave'),
                ('via', 'street'),
                ('in tablīnō', 'in the study'),
                ('in ātriō', 'in the atrium (main room)'),
                ('in triclīniō', 'in the dining-room'),
                ('in hortō', 'in the garden'),
                ('in culīnā', 'in the kitchen'),
                ('in viā', 'in the street'),
                ('scrībit', 'writes, is writing'),
                ('bibit', 'drinks, is drinking'),
                ('dormit', 'sleeps, is sleeping'),
                ('intrat', 'enters'),
                ('circumspectat', 'looks round'),
                ('cibus', 'food'),
                ('in mēnsā', 'on the table'),
                ('salit', 'jumps'),
                ('stat', 'stands'),
                ('stertit', 'snores'),
                ('lātrat', 'barks'),
                ('īrātus', 'angry'),
                ('pestis!', 'pest!'),
                ('furcifer!', 'scoundrel!'),
                ('exit', 'goes out'),
                ('faucēs', 'entrance door'),
                ('ātrium', 'main room'),
                ('cubiculum', 'bedroom'),
                ('tablīnum', 'study'),
                ('peristylium', 'garden court'),
                ('triclīnium', 'dining-room'),
                ('culīna', 'kitchen'),
                ('latrīna', 'lavatory'),
                ('iānua', 'front door'),
                ('impluvium', 'pool for rain water'),
                ('larārium', 'shrine of the household gods')
            ]
        },  # a section object
        {
            'title': 'In Villa',
            'exercises': [
                ('amīcus', 'friend'),
                ('ancilla', 'slave-girl, maid'),
                ('cēna', 'dinner'),
                ('cibus', 'food'),
                ('dominus', 'master'),
                ('dormit', 'sleeps'),
                ('intrat', 'enters'),
                ('laetus', 'happy'),
                ('laudat', 'praises'),
                ('mercātor', 'merchant'),
                ('quoque', 'also'),
                ('salūtat', 'greets'),
                ('vīsitat', 'visits, is visting'),
                ('vīllam', 'house'),
                ('pecūniam numerat', 'is counting money'),
                ('argentārius', 'banker'),
                ('respondet', 'replies'),
                ('in lectō recumbit', 'reclines on a couch'),
                ('cantat', 'is singing'),
                ('pāvōnem', 'peacock'),
                ('audit', 'hears'),
                ('nōn est', 'is not'),
                ('cēnam', 'dinner'),
                ('exspectat', 'is waiting for'),
                ('vituperat', 'blames, curses'),
                ('portat', 'is carring'),
                ('vīnum', 'wine'),
                ('gustat', 'tastes'),
                ('optimus', 'very good, excellent'),
                ('suāviter', 'sweetly'),
                ('dēlectat', 'pleases'),
                ('mox', 'soon'),
                ('et', 'and'),
                ('videt', 'sees'),
                ('cibum cōnsūmit', 'eats the food'),
                ('magnificē', 'magnificently, in style'),
                ('cēnat', 'dines, has dinner'),
                ('spectat', 'looks at'),
                ('laetissimus', 'very happy')
            ]
        }, # a section object
        {
            'title': 'Negotium',
            'exercises': [
                ('ad', 'to'),
                ('bibit', 'drinks'),
                ('circumspectat', 'looks around'),
                ('clāmat', 'shouts'),
                ('ecce!', 'look!'),
                ('et', 'and'),
                ('exit', 'goes out'),
                ('exspectat', 'waits for'),
                ('iānua', 'door'),
                ('īrātus', 'angry'),
                ('leō', 'lion'),
                ('magnus', 'big'),
                ('nāvis', 'ship'),
                ('nōn', 'not'),
                ('portat', 'carries'),
                ('respondet', 'replies'),
                ('rīdet', 'laughs, smiles'),
                ('salvē!', 'hello!'),
                ('surgit', 'gets up, stands up'),
                ('taberna', 'shop, inn'),
                ('videt', 'sees'),
                ('vīnum', 'wine'),
                ('in forō', 'in the forum'),
                ('negōtium agit', 'is working, is doing business'),
                ('pictor', 'painter, artist'),
                ('tōnsor', 'barber'),
                ('vēnālīcius', 'slave-dealer'),
                ('nōn venit', 'does not come'),
                ('ad vīllam', 'to the house'),
                ('iānuam pulsat', 'knocks at the door'),
                ('ad iānuam', 'to the door'),
                ('aperit', 'opens'),
                ('vocat', 'calls'),
                ('dūcit', 'leads, takes'),
                ('pictūram pingit', 'paints a picture'),
                ('fūstem', 'club'),
                ('tenet', 'holds, is holding'),
                ('verberat', 'strikes, is striking'),
                ('revenit', 'returns, comes back'),
                ('in tabernā', 'in the shop'),
                ('occupātus', 'busy'),
                ('in sellā', 'in the chair'),
                ('novāculam', 'razor'),
                ('barbam tondet', 'is trimming his beard'),
                ('poēta', 'poet'),
                ('versum recitat', 'recites a line, recites a verse'),
                ('scurrīlis', 'rude'),
                ('secat', 'cuts'),
                ('fluit', 'flows'),
                ('ē tabernā', 'out of the shop'),
                ('ad portum', 'to the harbour'),
                ('nāvem Syriam', 'Syrian ship'),
                ('prope nāvem', 'near the ship'),
                ('contentus', 'satisfied'),
                ('pulchra', 'beautiful'),
                ('linguam Latīnam', 'Latin language'),
                ('discit', 'is learning'),
                ('docta', 'skillful, educated'),
                ('satis', 'enough'),
            ]
        }, # a section object
        {
            'title': 'In Foro',
            'exercises': [
                ('agit', 'does'),
                ('ānulus', 'ring'),
                ('coquit', 'cooks'),
                ('cūr?', 'why?'),
                ('ē', 'from, out of'),
                ('ego', 'I'),
                ('ēheu!', 'oh dear!, oh no!'),
                ('habet', 'has'),
                ('inquit', 'says'),
                ('iūdex', 'judge'),
                ('mendāx', 'liar'),
                ('pecūnia', 'money'),
                ('perterritus', 'terrified'),
                ('poēta', 'poet'),
                ('quaerit', 'looks for, searches for'),
                ('quis?', 'who?'),
                ('reddit', 'gives back'),
                ('satis', 'enough'),
                ('sed', 'but'),
                ('signum', 'sign, seal'),
                ('tū', 'you'),
                ('vocat', 'calls'),
                ('argentāriam', 'banker\'s stall'),
                ('Graecus', 'Greek'),
                ('probus', 'honest'),
                ('nōn adest', 'is not here'),
                ('in Graeciā', 'in Greece'),
                ('semper', 'always'),
                ('ego reddō', 'I give back'),
                ('cēram', 'wax tablet'),
                ('ego imprimō', 'I press'),
                ('trādit', 'hands over'),
                ('capit', 'takes'),
                ('ad basilicam', 'to the law court'),
                ('Pompēiānus', 'a citizen of Pompeii'),
                ('cotīdiē', 'every day'),
                ('dēbet', 'owes'),
                ('testis', 'witness'),
                ('tū accūsās', 'you accuse'),
                ('tū rem nōn probās', 'you do not prove the case'),
                ('cēlat', 'is hiding'),
                ('ego convincō', 'i convict, I find guilty'),
                ('discēdit', 'departs, leaves'),
                ('ē tabernā', 'from the inn'),
                ('ēbrius', 'drunk'),
                ('ita vērō', 'yes')
            ]
        },  # a section object
        {
            'title': 'to be',
            'exercises': [
                ('sum', 'I am'),
                ('es', 'you (sing.) are'),
                ('est', 'he/she/it is'),
                ('summus', 'we are'),
                ('estis', 'you (pl.) are'),
                ('sunt', 'they are'),
                ('eram', 'I was'),
                ('eras', 'you (sing.) were'),
                ('erat', 'he/she/it was'),
                ('eramus', 'we were'),
                ('eratis', 'you (pl.) were'),
                ('erant', 'they were'),
            ]
        }, # a section object
        {
            'title': 'In Theatro',
            'exercises': [
                ('adest', 'is here'),
                ('adsunt', 'are here'),
                ('agricola', 'farmer'),
                ('ambulat', 'walks'),
                ('audit', 'hears'),
                ('clāmor', 'shout, uproar'),
                ('contendit', 'hurries'),
                ('fābula', 'play, story'),
                ('fēmina', 'woman'),
                ('hodiē', 'today'),
                ('iuvenis', 'young man'),
                ('meus', 'my mine'),
                ('multus', 'much'),
                ('multī', 'many'),
                ('optimus', 'very good, excellent'),
                ('petit', 'makes for, attacks'),
                ('plaudit', 'applauds'),
                ('puella', 'girl'),
                ('senex', 'old man'),
                ('spectat', 'looks at, watches'),
                ('stat', 'stands'),
                ('turba', 'crowd'),
                ('ubi?', 'where?'),
                ('urbs', 'city'),
                ('venit', 'comes'),
                ('āctōrēs', 'actors'),
                ('ōtiōsī', 'on holiday, idle'),
                ('nautae', 'sailors'),
                ('pāstōrēs', 'shepherds'),
                ('dē monte', 'down from the mountain'),
                ('per portam ruit', 'rushes through the gate'),
                ('fābulam dat', 'is putting on a play'),
                ('uxor', 'wife'),
                ('manet', 'remains, stays'),
                ('euge!', 'hurray!'),
                ('sēmisomnus', 'half-sleep'),
                ('tū clāmōrem facis', 'you are making a noise'),
                ('tū vexās', 'you annoy'),
                ('fābulam agunt', 'act a play'),
                ('tū dīcis', 'you say'),
                ('ruunt', 'rush'),
                ('mea columba', 'my dove, my dear'),
                ('dēliciae meae', 'my darling'),
                ('spectātōrēs', 'spectators'),
                ('tandem', 'at last'),
                ('in scaenā', 'on the stage'),
                ('fūnambulus', 'tight-rope walker'),
                ('nēmō', 'no one'),
            ]
        }, # a section object
        {
            'title': 'Felix',
            'exercises': [
                ('abest', 'is out, is absent'),
                ('aberat', 'was out, was absent'),
                ('cubiculum', 'bedroom'),
                ('emit', 'buys'),
                ('ferōciter', 'fiercely'),
                ('festīnat', 'hurries'),
                ('fortis', 'brave'),
                ('fūr', 'thief'),
                ('intentē', 'intently, carefully'),
                ('lībertus', 'freedman, ex-slace'),
                ('ōlim', 'once, some time ago'),
                ('parvus', 'small'),
                ('per', 'through'),
                ('postquam', 'after'),
                ('pulsat', 'hits, thumps'),
                ('quod', 'because'),
                ('rēs', 'thing'),
                ('scrībit', 'writes'),
                ('subitō', 'suddenly'),
                ('superat', 'overcomes, overpowers'),
                ('tum', 'then'),
                ('tuus', 'yours'),
                ('vēndit', 'sells'),
                ('vituperat', 'blames, curses'),
                ('pistōrēs', 'bakers'),
                ('pānem vēndēbant', 'were selling bread'),
                ('contentiōnem habēbat', 'was having an argument'),
                ('postulābat', 'was demanding'),
                ('incitābant', 'were urging on'),
                ('agitāvit', 'chased'),
                ('invītāvit', 'invited'),
                ('valdē commōtus', 'very moved, very much affected'),
                ('paene lacrimābat', 'was almost crying, was almost in tears'),
                ('excitāvit', 'aroused, woke up'),
                ('tōtam rem', 'the whole story'),
                ('nārrāvit', 'told'),
                ('parāvit', 'prepared'),
                ('post', 'after'),
                ('nunc', 'now'),
                ('sōlus', 'alone'),
                ('sorōrem', 'sister'),
                ('administrābat', 'was looking after'),
                ('nisi', 'except'),
                ('īnfāns', 'child, baby'),
                ('parvus', 'little'),
                ('necāvit', 'killed'),
                ('ita', 'in this way'),
                ('servāvit', 'saved'),
                ('igitur', 'therefore, and so'),
                ('avāvus', 'miser'),
                ('duo', 'two'),
                ('habitābat', 'was living'),
                ('fidēlis', 'faithful'),
                ('custōdit', 'is guarding'),
                ('serpēns', 'snake'),
                ('iacēbat', 'was lying'),
                ('timēbant', 'were afraid of, feared'),
                ('celeriter', 'quickly'),
                ('numquam', 'never'),
                ('servās', 'look after'),
            ]
        }, # a section object
        {
            'title': 'Cena',
            'exercises': [
                ('cēnat', 'dines'),
                ('cōnspicit', 'catches sight of'),
                ('cum', 'with'),
                ('facit', 'makes, does'),
                ('heri', 'yesterday'),
                ('ingēns', 'huge'),
                ('intellegit', 'understands'),
                ('lacrimat', 'weeps, cries'),
                ('mortuus', 'dead'),
                ('nārrat', 'tells, relates'),
                ('necat', 'kills'),
                ('nihil', 'nothing'),
                ('omnis', 'all'),
                ('parat', 'prepares'),
                ('prope', 'near'),
                ('rogat', 'asks'),
                ('tacitē', 'quitely'),
                ('tamen', 'however'),
                ('terret', 'frightens'),
                ('valdē', 'very much'),
                ('mīrābilis', 'extraordinary strange'),
                ('mīsit', 'sent'),
                ('discessit', 'departed, left'),
                ('pōculum hausit', 'drained his wine-cup'),
                ('ex urbe', 'from the city'),
                ('nox erat', 'it was night'),
                ('lūna plēna', 'full moon'),
                ('lūcēbat', 'was shining'),
                ('centuriōnem', 'centurion'),
                ('cōnspexit', 'caught sight of'),
                ('tunicam', 'tunic'),
                ('dēposuit', 'took off'),
                ('ēvānuit', 'vanished'),
                ('lupus', 'wolf'),
                ('appāruit', 'appeared'),
                ('ululāvit', 'howled'),
                ('cautē', 'cautionsly'),
                ('īnspexit', 'looked at, examined'),
                ('lapidea', 'made of stone'),
                ('rem intelleēxit', 'understod the truth'),
                ('versipellis', 'werewolf'),
                ('hospitēs', 'guests'),
                ('plausērunt', 'applauded'),
                ('tacēbant', 'were silent'),
                ('aliam', 'another'),
                ('priīmus', 'first'),
                ('gladiātōrem', 'gladiator'),
                ('prope amphitheātrum', 'near the amphitheatre'),
                ('secundus', 'second'),
                ('terruit', 'frightened'),
                ('vibrābat', 'was brandishing, was waving'),
                ('in arēnā', 'in the arena'),
                ('īnsānus', 'mad, crazy'),
                ('homō', 'human being, man'),
                ('trāxit', 'dragged'),
                ('nōtissimus', 'very well-known'),
                ('vīvit', 'is alive'),
                ('umbra', 'ghost'),
                ('explicāvit', 'explained'),
                ('valē', 'goodbye'),
                ('timidē', 'nervously'),
                ('prōcēdēbant', 'were proceeding, were advancing'),
                ('nūllae stēllae', 'no stars'),
                ('in caelō', 'in the sky'),
                ('dēsertae', 'deserted'),
                ('fēlēs', 'cat'),
                ('ruērunt', 'rushed'),
                ('dē vītā dēspērābant', 'were in despair of their lives'),
                ('fēcērunt', 'made'),
                ('sollicitī', 'worried, anxious'),
                ('pessimam', 'very bad'),
                ('coxit', 'cooked'),
                ('fēcit', 'has done'),
                ('stilī', 'pens (used for writing on wax tablets)'),
                ('in locō propriō', 'in the right place'),
                ('vīdit', 'saw'),
                ('crīnēs', 'hair'),
                ('optimē', 'very well'),
                ('compōnis', 'arrange'),
                ('stolam', 'dress'),
                ('fortasse', 'perhaps'),
                ('dīligenter', 'carefully'),
                ('cūrās', 'look after')
            ]
        }, # a section object
        {
            'title': 'Gladiatores',
            'exercises': [
                ('agitat', 'chases, hunts'),
                ('cōnsūmit', 'eats'),
                ('dūcit', 'leads, takes'),
                ('eum', 'him'),
                ('facile', 'easily'),
                ('ferōx', 'fierce'),
                ('gladius', 'sword'),
                ('hic', 'this'),
                ('ignāvus', 'cowardly'),
                ('nūntius', 'messenger'),
                ('pēs', 'foot'),
                ('porta', 'gate'),
                ('postulat', 'demands'),
                ('puer', 'boy'),
                ('pugnat', 'fights'),
                ('saepe', 'often'),
                ('sanguis', 'blood'),
                ('silva', 'wood'),
                ('spectāculum', 'show, spectacle'),
                ('statim', 'at once'),
                ('tōtus', 'whole'),
                ('senātor Rōmānus', 'a Roman senator'),
                ('magnificā', 'magnificent'),
                ('inimīcī', 'enemies'),
                ('turbulentī', 'rowdy, disorderly'),
                ('splendidum', 'splendid'),
                ('ēdidit', 'presented'),
                ('diem nātālem', 'birthday'),
                ('celebrābat', 'was celebrating'),
                ('vēnērunt', 'came'),
                ('cīvēs', 'citizens'),
                ('complēbant', 'were filling'),
                ('nūntiābant', 'were announcing'),
                ('vīgintī', 'twenty'),
                ('rētiāriī', 'net-fighters'),
                ('murmillōnēs', 'heavily armed gladiators'),
                ('bēstiāriī', 'beast-fighters'),
                ('bēstiās', 'beasts'),
                ('quam celerrimē', 'as quick as possible'),
                ('vehementer', 'loudly, violently'),
                ('tacuērunt', 'fell silent'),
                ('tuba', 'trumpet'),
                ('sonuit', 'sounded'),
                ('pugnam commīsērunt', 'began the fight'),
                ('victōrēs', 'victors, winners'),
                ('expedītī', 'lightly armed'),
                ('ēvītāvērunt', 'avoided'),
                ('ignāvī', 'cowardly'),
                ('callidī', 'clever, cunning'),
                ('dēcipiunt', 'are deceiving, are fooling'),
                ('frūstrā', 'in vain'),
                ('prōvocāvērunt', 'challenged'),
                ('ūnus', 'one'),
                ('graviter', 'seriously'),
                ('vulnerāvērunt', 'wounded'),
                ('alterum', 'the second, the other'),
                ('missiōnem', 'release'),
                ('mortem', 'death'),
                ('pollicem vertit', 'turned his thumb up'),
                ('interfēcērunt', 'killed'),
                ('vēnātiō', 'hunt'),
                ('iterum', 'again'),
                ('cervī', 'deer'),
                ('ēsuriēbant', 'were hungry'),
                ('fortissimī', 'very brave'),
                ('retinet', 'is holding back'),
                ('trēs', 'three'),
                ('audācissimē', 'very boldly'),
                ('recubuērunt', 'lay down'),
                ('obdormīvērunt', 'went to sleep'),
                ('īrātissimī', 'very angry'),
                ('rīdiculum', 'ridiculous, silly'),
                ('ēdēbat', 'was presenting'),
                ('fugiēbant', 'began to run away, began to flee'),
                ('suōs', 'their'),
                ('dēstrīnxērunt', 'drew'),
                ('attonitus', 'astonished'),
                ('trīstis', 'sad'),
                ('pedem', 'foot, paw'),
                ('ostendit', 'showed'),
                ('spīnam', 'thorn'),
                ('dolet', 'hurts'),
                ('benignus', 'kind'),
                ('fremuit', 'roared'),
                ('adiuvō', 'help'),
                ('extrāxit', 'pulled out'),
                ('posteā', 'afterwards'),
                ('comprehendērunt', 'arrested'),
                ('Chrīstiānus', 'Christian'),
                ('olfēcit', 'smelled, sniffed'),
                ('lambēbat', 'began to lick'),
                ('agnōvit', 'recognised'),
                ('ad salūtem', 'to safety')
            ]
        }, # a section object
        {
            'title': 'Thermae Stage 9',
            'exercises': [
                ('in palaestrā', 'in the exercise area'),
                ('discum', 'discus'),
                ('ferēbat', 'was carrying'),
                ('āthlētās', 'athletes'),
                ('statuās', 'statues'),
                ('posuērunt', 'have placed, have put up'),
                ('porticus', 'colonnade'),
                ('offerēbant', 'were offering'),
                ('in mediā turbā', 'in the middle of the room'),
                ('āthlēta ille', 'that athlete'),
                ('novum', 'new'),
                ('prōcessit', 'proceeded, advanced'),
                ('ēmīsit', 'threw'),
                ('longē', 'a long way, far'),
                ('per aurās ēvolāvit', 'flew through the air'),
                ('invēnit', 'found'),
                ('rediit', 'came back'),
                ('nōn accēpit', 'did not accept'),
                ('trādidit', 'handed over'),
                ('percussit', 'struck'),
                ('nāsum frāctum', 'a broken nose'),
                ('māne', 'in the morning'),
                ('togam', 'toga'),
                ('domina', 'madam'),
                ('dōnum', 'present, gift'),
                ('hae togae', 'these togas'),
                ('sordidae', 'dirty'),
                ('intus', 'inside'),
                ('aliās', 'other'),
                ('ēlēgit', 'chose'),
                ('haec', 'this'),
                ('quantī est?', 'how much is it?'),
                ('quīnquāgintā dēnāriōs', 'fifty denarii'),
                ('cupiō', 'I want'),
                ('decem', 'ten'),
                ('quadrāgintā', 'forty'),
                ('quīndecim', 'fifteen'),
                ('pulcherrima', 'very beautiful'),
                ('nimium', 'too much'),
                ('trīgintā', 'thirty'),
                ('cōnsentiō', 'I agree'),
                ('ego tibi grātiās maximās agō', 'I thank you very much'),
                ('in apodytēriō', 'in the changing room'),
                ('num dormīs?', 'surely you are not asleep?'),
                ('suam', 'his'),
                ('induit', 'is putting on'),
                ('abī!', 'go away!'),
                ('pauper', 'poor'),
                ('geris', 'your are wearing'),
                ('parce!', 'spare me! have pity on me!'),
                ('pauperrimus', 'very poor'),
                ('aegra', 'sick, ill'),
                ('līberōs', 'children'),
                ('audiunt', 'listen to'),
                ('agnōscit', 'recognises'),
                ('cupit', 'wants'),
                ('dat', 'gives'),
                ('diēs', 'day'),
                ('ēmittit', 'throws, sends out'),
                ('fert', 'brings, carries'),
                ('hospes', 'guest'),
                ('ille', 'that'),
                ('īnspicit', 'looks at, examines'),
                ('medius', 'middle'),
                ('offert', 'offers'),
                ('prōcēdit', 'proceeds, advances'),
                ('pulcher', 'beautiful')
            ]
        }, # a section object
        {
            'title': 'Rhetor Stage 10',
            'exercises': [
                ('contrōversia', 'debate'),
                ('ībant', 'were going'),
                ('rhētor', 'teacher'),
                ('longa', 'long'),
                ('docēbat', 'used to teach'),
                ('hanc', 'this'),
                ('meliōrēs quam', 'better than'),
                ('minimē!', 'no!'),
                ('sententiam', 'opinion'),
                ('argūmentum', 'proof'),
                ('barbarōs', 'barbarians'),
                ('imperium', 'empire'),
                ('pācem', 'peace'),
                ('servāmus', 'keep preserve'),
                ('architectī', 'builders, architects'),
                ('pontēs', 'bridges'),
                ('ubīque', 'everywhere'),
                ('aedificāmus', 'build'),
                ('maior quam', 'greater than, bigger than'),
                ('postrēmō', 'lastly'),
                ('deī', 'gods'),
                ('dant', 'give'),
                ('ignāvī', 'lazy'),
                ('deinde', 'then'),
                ('surrēxit', 'got up'),
                ('miserandī', 'pathetic, pitiful'),
                ('imitātōrēs', 'imitators'),
                ('auctōrēs', 'creators'),
                ('librōs', 'books'),
                ('legitis', 'read'),
                ('rīsērunt', 'laughted'),
                ('frātrēs', 'brothers'),
                ('īnstitor', 'pedlar, street vendor'),
                ('ad ēos', 'to them'),
                ('fēlīcēs', 'lucky'),
                ('quam!', 'how!'),
                ('dā!', 'give!'),
                ('dissentiēbant', 'were arguing'),
                ('stultissimī', 'very stupid'),
                ('abīte!', 'go away!'),
                ('retineō', 'am keeping'),
                ('abiērunt', 'went away'),
                ('in terram', 'onto the ground'),
                ('dēiēcit', 'threw'),
                ('in piscīnam', 'into the fish-pond'),
                ('venīte hūc!', 'come here!'),
                ('philosophus', 'philosopher'),
                ('sōlus', 'lonely'),
                ('vōsne estis contentī?', 'are you satisfied?'),
                ('Graeculī', 'poor Greeks'),
                ('artificēs', 'artists'),
                ('praemium', 'profit, reward'),
                ('susurrāvit', 'whispered, muttered'),
                ('Aegyptius', 'Egyptian'),
                ('caupō', 'innkeeper'),
                ('Neptūnus', 'Neptune (god of the sea)'),
                ('dēlēvit', 'has destroyed'),
                ('antīquus', 'old, ancient'),
                ('in pyramide', 'in a pyramid'),
                ('clausit', 'shut'),
                ('eam', 'her'),
                ('postrīdiē', 'on the next day'),
                ('marītum', 'husband'),
                ('incendium', 'blaze, fire'),
                ('ardēbat', 'was on fire'),
                ('īnfēliīx', 'unlucky'),
                ('cēpit', 'took'),
                ('āmīsit', 'lost'),
                ('abit', 'goes away'),
                ('accipit', 'accepts'),
                ('callidus', 'clever, cunning'),
                ('exclāmat', 'exclaims'),
                ('frāter', 'brother'),
                ('habitat', 'lives'),
                ('invenit', 'finds'),
                ('liber', 'book'),
                ('nōs', 'we'),
                ('nūntiat', 'announces'),
                ('pāx', 'peace'),
                ('portus', 'harbour'),
                ('quam', 'than'),
                ('servat', 'saves, looks after'),
                ('suus', 'his, her, their'),
                ('tacet', 'is silent, is quite'),
                ('uxor', 'wife'),
                ('vehementer', 'violently, loudly'),
                ('vōs', 'you (plural)')
            ]
        }, # a section object
        {
            'title': 'Candidati State 11',
            'exercises': [
                ('candidātus', 'candidate'),
                ('favent', 'favour, give support to'),
                ('vir dīves', 'a rich man'),
                ('vir nōbilis', 'a man of noble birth'),
                ('crēdunt', 'trust, have faith in'),
                ('sibi dīxit', 'said to himself'),
                ('gēns nostra', 'our family'),
                ('rem cōgitābat', 'was considering the problem'),
                ('scrīptor', 'sign-writer'),
                ('cōnsilium cēpit', 'had an idea'),
                ('mūrum', 'wall'),
                ('scrībe!', 'write!'),
                ('titulum', 'notice, slogan'),
                ('placetne tibi?', 'does it please you? does it suite you?'),
                ('scrīpsit', 'wrote'),
                ('asinus', 'ass, donkey'),
                ('senior', 'the elder'),
                ('ērāde!', 'rub out! erase!'),
                ('īnscrīptiōnem', 'writing'),
                ('ērāsit', 'rubbed out, erased'),
                ('dēsistite!', 'stop!'),
                ('intrō īte!', 'go inside!'),
                ('rem cōnfēcit', 'finished the job'),
                ('tertium', 'third'),
                ('addidit', 'added'),
                ('līberālissimī', 'very generous'),
                ('babae!', 'hey!'),
                ('quō?', 'where?'),
                ('fautōrēs', 'supporters'),
                ('quīnque', 'five'),
                ('prōmīsit', 'promised'),
                ('tantum', 'only'),
                ('mendācissimus', 'very deceitful'),
                ('ad amphitheātrum', 'at the amphitheatre'),
                ('convenīmus', 'gather, meet'),
                ('ōrātiōnēs', 'speeches'),
                ('mēcum', 'with me'),
                ('dē tē', 'about you'),
                ('perīculōsam', 'sangerous'),
                ('suscipis', 'you are taking on'),
                ('exeunt', 'they go out'),
                ('dīvīsor', 'agent (hired to distribute bribes at elections'),
                ('festīnāte!', 'hurry!'),
                ('amīcissimī', 'very friendly, very good friends'),
                ('tacē!', 'shut up! be quite!'),
                ('ūtilissimī', 'very useful'),
                ('caudex', 'blockhead, idiot'),
                ('scissa', 'torn'),
                ('rapuērunt', 'seized, grabbed'),
                ('auxilium', 'help'),
                ('effūgit', 'escaped'),
                ('ibi', 'there'),
                ('candidus', 'dazzling white'),
                ('capit', 'takes'),
                ('cīvis', 'citizen'),
                ('convenit', 'gathers, meets'),
                ('crēdit', 'trusts, believes'),
                ('dē', 'about'),
                ('favet', 'supports'),
                ('invītat', 'invites'),
                ('it', 'goes'),
                ('legit', 'reads'),
                ('līberālis', 'generous'),
                ('minimē!', 'no!'),
                ('noster', 'our'),
                ('nunc', 'now'),
                ('placet', 'it pleases'),
                ('prīmus', 'first'),
                ('prōmittit', 'promises'),
                ('pugna', 'fight'),
                ('senātor', 'senator'),
                ('sollicitus', 'worried, anxious'),
                ('stultus', 'stupid'),
                ('valē!', 'goodbye!'),
                ('verberat', 'strikes, beats'),
                ('vir', 'man')
            ]
        }, # a section object
        {
            'title': 'Vesuvius Stage 12',
            'exercises': [
                ('tremōrēs', 'tremors'),
                ('tremuit', 'shook'),
                ('sēnsī', 'felt'),
                ('agēbās', 'were doing'),
                ('epistulās', 'letters'),
                ('dictābam', 'was dictating'),
                ('nūbem', 'cloud'),
                ('familiam', 'household'),
                ('larārium', 'shrine'),
                ('laribus', 'household gods'),
                ('sacrificium', 'sacrifice'),
                ('iamprīdem', 'a long time ago'),
                ('fundum', 'farm'),
                ('vīlicō', 'farm manager, bailiff'),
                ('sonōs', 'noises'),
                ('fīliae', 'daughters'),
                ('parentēs', 'parents'),
                ('pervēnī', 'reached, arrived at'),
                ('pretiōsae', 'precious'),
                ('iste mōns', 'that (terrible) mountain'),
                ('scio', 'know'),
                ('nihil cūrō', 'I don\'t care'),
                ('pavor', 'panic'),
                ('cinis', 'ash'),
                ('iam', 'now'),
                ('dēnsior', 'thicker'),
                ('incidēbat', 'was falling'),
                ('flammae', 'flames'),
                ('iter', 'journey, progress'),
                ('difficile', 'difficult'),
                ('valeō', 'I feel well'),
                ('dēcidit', 'fell down'),
                ('exanimātus', 'unconscious'),
                ('templum', 'temple'),
                ('proximum', 'nearest'),
                ('lībertātem', 'freedom'),
                ('respīrāvit', 'recovered breath, recovered consciousness'),
                ('tūtī', 'safe'),
                ('dea', 'goddess'),
                ('sine dubiō', 'without doubt'),
                ('fīnis', 'end'),
                ('ātra', 'black'),
                ('dēscendēbat', 'was coming down'),
                ('plūrimī', 'most'),
                ('obstinātē', 'stubbornly'),
                ('ruīnās', 'ruins, wreckage'),
                ('fūmum', 'smoke'),
                ('moribundus', 'almost dead'),
                ('sēmirutus', 'half-collapsed'),
                ('sēnsim', 'slowly, gradually'),
                ('accidit', 'happened'),
                ('pariēs', 'wall'),
                ('iubeō', 'order'),
                ('periērunt', 'have died, have perished'),
                ('moritūrus', 'going to die'),
                ('recūsāvit', 'refused'),
                ('superfuit', 'has survived'),
                ('exspīrāvit', 'died'),
                ('trīste', 'sadly'),
                ('āmittit', 'loses'),
                ('complete', 'fills'),
                ('custōdit', 'guards'),
                ('epistula', 'letter'),
                ('fortiter', 'bravely'),
                ('frūstrā', 'in vain'),
                ('fugit', 'runs away, flees'),
                ('fundus', 'farm'),
                ('iacet', 'lies'),
                ('igitur', 'therefore'),
                ('mīrābilis', 'strange, extraodinary'),
                ('mittit', 'sends'),
                ('mōns', 'mountain'),
                ('optimē', 'very well'),
                ('paene', 'nearly, almost'),
                ('sentit', 'feels'),
                ('tandem', 'at last'),
                ('templum', 'temple'),
                ('terra', 'ground, land'),
                ('timet', 'is afraid, fears'),
            ]
        }, # a section object
    ]
}
