# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Latin year 8
'''
ZHENGLIN_YEAR8 = {
    'title': 'Cambridge Latin Course Book II',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'latin',
    'sections':[
        {
            'title': 'in Britanniā',
            'exercises': [
                ('Britanniā: Britannia', 'Britain'),
                ('dēplōrant: dēplōrāre', 'complain about'),
                ('pluit', 'it is raining'),
                ('sōlem: sōl', 'sun'),
                ('Ītaliam: Ītalia', 'Italy'),
                ('redīre volō', 'I want to return'),
                ('aquam: aqua', 'water'),
                ('bibere nōn possum', 'I cannot drink'),
                ('foeda', 'foul, filthy'),
                ('pavīmentum', 'floor'),
                ('lavat: lavāre', 'wash'),
                ('labōrāre nōlō', 'I do not want to work'),
                ('fessus', 'tired'),
                ('advenit: advenīre', 'arrive'),
                ('apud Canticōs', 'among the Cantici'),
                ('coniūrātiōnem: coniūrātiō', 'plot'),
                ('vulnerātus', 'wounded'),
                ('metallum', 'a mine'),
                ('hospes', 'host'),
                ('quamquam', 'although'),
                ('ferrum', 'iron'),
                ('effodiēbant: effodere', 'dig'),
                ('ad sē', 'to him'),
                ('inūtilis', 'useless'),
                ('carnificibus: carnifex', 'executioner'),
                ('nōmen', 'name'),
                ('vindicāre voluit', 'wanted to avenge'),
                ('itaque', 'and so'),
                ('ubi', 'when'),
                ('cēterī', 'the others, the rest'),
                ('pugiōnem: pugiō', 'dagger'),
                ('custōdēs: custōs', 'guard'),
                ('ēlūsit: ēlūdere', 'slip past'),
                ('manūs ...extendit', 'stretched out his hands'),
                ('veniam petīvit', 'begged for mercy'),
                ('saeviēbat: saevīre', 'be in a rage'),
                ('cōnsciī: cōnscius', 'accomplice'),
                ('supplicium', 'death penalty'),
                ('poscō: poscere', 'demand'),
                ('nocēns', 'guilty'),
                ('innocentēs: innocēns', 'innocent'),
                ('coniūrābant: coniūraāre', 'plot'),
                ('invītus', 'unwilling, relucant'),
                ('in āream', 'into the courtyard'),
                ('in ōrdinēs', 'in rows'),
                ('sē īnstrūxērunt: sē īnstruere', 'draw oneself up'),
                ('per ōrdinēs', 'along the rows'),
                ('sēcum', 'with him'),
                ('rēx', 'king'),
                ('equitēs: eques', 'horseman'),
                ('equō: equus', 'horse'),
                ('puerī puellaeque', 'the boys and girs'),
                ('geminī', 'twins'),
                ('simulac', 'as soon as'),
                ('īnsolēns', 'rude, insolent'),
                ('ērūpit: ērumpere', 'break away'),
                ('nōnnūllī', 'some, several'),
                ('retrāxērunt: retrahere', 'drag back'),
                ('sē recēpit: sē recipere', 'recover'),
                ('illud', 'that'),
                ('pūnīre', 'punish'),
                ('facile', 'easy'),
                ('agrōs: ager', 'field'),
                ('segetem: seges', 'crop, harvest'),
                ('frūmentum', 'grain'),
                ('horreum', 'barn, granary'),
                ('intulērunt: īnferre', 'bring in'),
                ('arātōrēs: arātor', 'ploughman'),
                ('magister', 'foreman'),
                ('nōnne?', 'surely?'),
                ('pareest: pareesse', 'be in charge of'),
                ('eī', 'to him'),
                ('perītissimus: perīrus', 'skillful'),
                ('sōlus', 'alone, only'),
                ('rem rūsticam', 'the farming'),
                ('cūrāre', 'look after, supervise'),
                ('simulatque', 'as soon as'),
                ('hī', 'these'),
                ('ferunt: ferre', 'bring'),
                ('ignāvīs: ignāvus', 'lazy'),
                ('aedificium', 'building'),
                ('dīra', 'dreadful'),
                ('taurus', 'bull'),
                ('animal', 'animal'),
                ('impetum: impetus', 'attack'),
                ('neglegēns', 'careless'),
                ('Britannīs: Britannī', 'Britons'),
                ('adveniō, advenīre, advēnī', 'arrive'),
                ('alter', 'the other, the second'),
                ('cantō, cantāre, cantāvī', 'sing'),
                ('dīcō, dīcere, dīxī', 'say'),
                ('excitō, excitāre, excitāvī', 'arouse, wake up'),
                ('interficiō, interficere, interfēcī', 'kill'),
                ('ita vērō', 'yes'),
                ('nōlō', 'I do not want'),
                ('novus', 'new'),
                ('nūllus', 'not any, no'),
                ('possum', 'I can, I am able'),
                ('ruō, ruere, ruī', 'rush'),
                ('sē', 'himself'),
                ('trahō, trahere, trāxī', 'drag'),
                ('vīta', 'life'),
                ('volō', 'I want'),
                ('vulnerō, vulnerāre, vulnerāvī', 'wound'),
            ]
        },
        {
            'title': 'Apud Salvium',
            'exercises': [
                ('ōrnātrīcēs: ōrnātrīx', 'hairdresser'),
                ('dīmittit: dīmittere', 'send away, dismiss'),
                ('crūdēlis', 'cruel'),
                ('Londiniō: Londinium', 'London'),
                ('amīcās:amīca', 'friend'),
                ('relinquere', 'leave'),
                ('levis', 'changeable, inconsistent'),
                ('vīllam rūsticam: vīlla rūstica', 'house in the country'),
                ('etiam', 'even'),
                ('ab urbe', 'from the city'),
                ('tū ipsa', 'you yourself'),
                ('pretium', 'price'),
                ('libenter', 'gladly'),
                ('ēlegāns', 'tasteful, elegant'),
                ('hiems', 'winter'),
                ('appropinquat: appropinquāre', 'approach'),
                ('commodum: commodus', 'convenient'),
                ('hiemāre', 'spend the winter'),
                ('novem', 'nine'),
                ('lacrimāns', 'weeping, crying'),
                ('anus', 'old woman'),
                ('quid vīs?', 'what do you want?'),
                ('necesse', 'necessary'),
                ('familiārem: familiāris', 'relation, relative'),
                ('diū', 'for a long time'),
                ('domina ipsa', 'the mistress herself'),
                ('verrere', 'sweep'),
                ('scōpās: scōpae', 'broom'),
                ('lentē', 'slowly'),
                ('decōrum: decōrus', 'right, proper'),
                ('lacrimīs sē trādidit', 'burst into tears'),
                ('miserrima', 'very miserable, very sad'),
                ('diūtius', 'any longer'),
                ('nōlī lacrimāre', 'don\'t cry'),
                ('pūrum: pūrus', 'clean, spotless'),
                ('mel', 'honey'),
                ('ōsculum', 'kiss'),
                ('ērubēscēns', 'blushing'),
                ('vix', 'hardly, scarcely'),
                ('urnam: urna', 'bucket'),
                ('sōla', 'alone, on her own'),
                ('nitidum: nitidus', 'gleaming, brilliant'),
                ('bene', 'well'),
                ('nam', 'for'),
                ('inēlegāns', 'unattractive'),
                ('id', 'it'),
                ('ōrāre', 'decorate'),
                ('armārium', 'chest, cupboard'),
                ('aēnea', 'made of bronze'),
                ('candēlābrum', 'lamp-stand, candelabrum'),
                ('aureum: aureus', 'golden, made of gold'),
                ('age!', 'come on!'),
                ('īre', 'go'),
                ('mī Salvī!', 'my dear Salvius!'),
                ('heus!', 'hey!'),
                ('cārissime', 'dearest'),
                ('aliquid', 'something'),
                ('cēdit: cēdere', 'give in, give away'),
                ('bene!', 'good!'),
                ('convēnī: convenīre', 'meet'),
                ('tot', 'so many'),
                ('cōmis', 'courteous, friendly'),
                ('urbānus', 'smart, fashionable'),
                ('paucī', 'a few'),
                ('mīlitābam: mīlitāre', 'be a solider'),
                ('cognōscēbam: cognōscere', 'get to know'),
                ('mīlitēs: mīles', 'soldier'),
                ('in eō', 'in it'),
                ('num tū... extrāxistī?', 'surely you did not take?'),
                ('prō dī immortālēs!', 'heavens above!'),
                ('ō mē miserum!', 'oh wretched me! oh dear!'),
                ('exspectātissimus: exspectātus', 'welcome'),
                ('modicam', 'ordinary, little'),
                ('ostreās: ostrea', 'oyster'),
                ('garum', 'sauce'),
                ('clādēs', 'disaster'),
                ('terribilis', 'terrible'),
                ('interpellāvit: interpellāre', 'interrupt'),
                ('tantam', 'so great, such a great'),
                ('commemorāre', 'talk about'),
                ('sē convertit: sē convertere', 'turn'),
                ('ōrnātum: ōrnātus', 'elaborately furnished, decorated'),
                ('ēlegantius', 'more tasteful'),
                ('tripodes', 'tripods'),
                ('argenteī: argenteus', 'made of silver'),
                ('aulam: aula', 'palace'),
                ('quotannīs', 'every year'),
                ('imperātōrem: imperātor', 'emperor'),
                ('honōrāre', 'honour'),
                ('arcā: arca', 'strong-box, chest'),
                ('cellārium: cellārius', 'steward'),
                ('urna', 'jar, jug'),
                ('amphoram: amphora', 'wine-jar'),
                ('dēmōnstrat: dēmōnstrāre', 'point out, show'),
                ('importat: importāre', 'import'),
                ('aurāta', 'gilded, gold-plated'),
                ('nōn dēbēs', 'you shouldn\'t, you mustn\'t'),
                ('aliquid', 'something'),
                ('apud', 'among, at the house of'),
                ('attonitus', 'astonished'),
                ('aula', 'palace'),
                ('cotīdiē', 'every day'),
                ('decōrus', 'right, proper'),
                ('dēleō, dēlēre, dēlēvī', 'destroy'),
                ('deus', 'god'),
                ('difficilis', 'difficult'),
                ('dīligenter', 'carefully'),
                ('domina', 'mistress'),
                ('dōnum', 'present, gift'),
                ('fidēlis', 'faithful, loyal'),
                ('ipse, ipsa', 'himself, herself'),
                ('iste', 'that'),
                ('marītus', 'husband'),
                ('necesse', 'necessary'),
                ('num?', 'surely...not?'),
                ('quam', 'how'),
                ('quamquam', 'although'),
                ('-que', 'and'),
                ('rēx', 'king'),
                ('ubi', 'when'),
            ]
        }, # a section object
        {
            'title': 'Rex Cogidubnus',
            'exercises': [
                ('in prīmā parte', 'in the forefront'),
                ('virgās: virga', 'rod, stick'),
                ('praecursōrēs: praecursor', 'forerunner (sent ahead of a procession to clear the way'),
                ('equitābant: equitāre', 'ride'),
                ('flōrēs: flōs', 'flower'),
                ('facere dēbeō', 'ought to do'),
                ('ēmovēre', 'move, clear away'),
                ('impedīre', 'delay, hinder'),
                ('fossās: fossa', 'ditch'),
                ('dēsiluērunt: dēsilīre', 'jump down'),
                ('impavidī: impavidus', 'fearless'),
                ('cōnsistēbant: cōnsistere', 'stand one\'s ground, stand firm'),
                ('plaustrum', 'wagon, cart'),
                ('claudēbat: claudere', 'block'),
                ('movēre', 'move'),
                ('rotam: rota', 'wheel'),
                ('anteā', 'before'),
                ('surdus', 'deaf'),
                ('dēicite!', 'throw!'),
                ('resistēbant: resistere', 'resist'),
                ('cachinnāns', 'laughing, cackling'),
                ('molestissimī: molestus', 'troublesome'),
                ('caerimōnia', 'ceremony'),
                ('ātrium', 'hall'),
                ('illī', 'they'),
                ('prīncipēs: prīnceps', 'chief, chieftain'),
                ('Britannicī: Britannicus', 'British'),
                ('sermōnēs: sermō', 'conversation'),
                ('inter sē', 'among themselves, with each other'),
                ('multitūdō', 'crowd'),
                ('effigiēs cērāta', 'wax image'),
                ('bona', 'good'),
                ('fabrī: faber', 'craftsman'),
                ('prōcubuit: prōcumbere', 'fall'),
                ('claudicābat: claudicāre', 'be lame, limp'),
                ('vīnum lībāvit', 'poured wine as an offering'),
                ('sacerdōtēs: sacerdōs', 'priest'),
                ('victimās: victima', 'victim'),
                ('agnus', 'lamb'),
                ('niveus', 'snow-white'),
                ('sacrificāvit: sacrificāre', 'sacrifice'),
                ('umerōs: umerus', 'shoulder'),
                ('sustulērunt: tollere', 'raise, lift up'),
                ('sollemniter cantābant', 'were chanting solemnly'),
                ('rogus', 'pyre'),
                ('cum magnā dignitāte', 'with great dignity'),
                ('facem: fax', 'torch'),
                ('tangēbant: tangere', 'touch'),
                ('liquābant: liquāre', 'melt'),
                ('aquila', 'eagle'),
                ('ēvolāvit: ēvolāre', 'fly out'),
                ('arcessunt: arcessere', 'summon, send for'),
                ('animus', 'soul, spirit'),
                ('ascendit: ascendere', 'climb, rise'),
                ('lūdī fūnebrēs', 'funeral games'),
                ('pompam: pompa', 'procession'),
                ('ad lītus', 'to the sea-shore'),
                ('gentēs: gēns', 'tribe'),
                ('competītōrēs: competītor', 'competitor'),
                ('certābant: certāre', 'compete'),
                ('vincēbant: vincere', 'be victorious, win'),
                ('longius', 'further'),
                ('certāmen nāvāle', 'boat-race'),
                ('inter Canticōs et Rēgnēnsēs', 'between the Cantici and the Regnenses'),
                ('superbus', 'arrogant, proud'),
                ('undās: unda', 'wave'),
                ('in lītore', 'on the shore'),
                ('procul', 'far off'),
                ('in marī', 'in the sea'),
                ('saxum', 'rock'),
                ('mēta', 'turning-point'),
                ('dīrigēbat: dīrigere', 'steer'),
                ('piror', 'in front, first'),
                ('ad dextram', 'to the right'),
                ('nāvigāre', 'sail'),
                ('scopulus', 'reef'),
                ('sub', 'under'),
                ('latet: latēre', 'lie hidden'),
                ('vītāre', 'avoid'),
                ('ignōrābat', 'did not know about'),
                ('cursum rēctum', 'a straight course'),
                ('timidī: timidus', 'fearful, frightened'),
                ('dērīdēbat: dērīdēre', 'mock, jeer at'),
                ('incurrit: incurrere', 'run onto, collide'),
                ('summersa', 'sunk'),
                ('intereā', 'meanwhile'),
                ('cum summā cūrā', 'with the greatest care'),
                ('circum', 'around'),
                ('incolumis', 'safe'),
                ('oculōs: oculus', 'eye'),
                ('eīs', 'for them'),
                ('natābant: natāre', 'swim'),
                ('in summō saxō', 'on the top of the rock'),
                ('madidus', 'soaked through'),
                ('haerēbat: haerēre', 'cling'),
                ('agmen', 'column (of men), procession'),
                ('alius', 'other, another'),
                ('claudō, claudere, clausī', 'shut, block'),
                ('commodus', 'convenient'),
                ('dēbeō, dēbēre, dēbuī', 'own, ought'),
                ('equus', 'horse'),
                ('etiam', 'even'),
                ('impediō, impedīre, impedīvī', 'delay, hinder'),
                ('lectus', 'couch'),
                ('lentē', 'slowly'),
                ('lītus', 'sea-shore'),
                ('mare', 'sea'),
                ('miser', 'miserable, wretched'),
                ('nauta', 'sailor'),
                ('quī', 'who'),
                ('redeō, redīre, redī', 'return, go back'),
                ('teneō, tenēre, tenuī', 'hold'),
                ('vincō, vincere, vīcī', 'win')
            ]
        }, # a section object
    ]
}
