# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Spanish year 7
'''
ZHENGLIN_YEAR7 = {
    'title': 'Spanish Year 7',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections':[
        {
            'title': 'Numbers 1 - 10',
            'exercises': [
                (r'uno', r'1'),
                (r'dos', r'2'),
                (r'tres', r'3'),
                (r'cuatro', r'4'),
                (r'cinco', r'5'),
                (r'seis', r'6'),
                (r'sieta', r'7'),
                (r'ocho', r'8'),
                (r'nueve', r'9'),
                (r'diez', r'10'),
                (r'n\'umeros', r'numbers')
            ]
        },  # a section object
        {
            'title': 'Family',
            'exercises': [
                (r'En mi familia, hey...', r'In my family, there is/are...'),
                (r'y', r'and'),
                (r'mi', r'my (singular noun)'),
                (r'mis', r'my (plural noun)'),
                (r'los abuelos', r'grandparents'),
                (r'el abuelo', r'grandfather'),
                (r'la abuela', r'grandmother'),
                (r'los padres', r'parents'),
                (r'el padre', r'the father'),
                (r'la madre', r'the mother'),
                (r'el padrasto', r'step dad'),
                (r'la madrastra', r'step mother'),
                (r'el marido', r'husband'),
                (r'la esposa??', r'wife'),
                (r'los parientes', r'the relatives'),
                (r'la t\'ia', r'aunt'),
                (r'el t\'io', r'uncle'),
                (r'los t\'ios', r'uncles'),
                (r'las t\'ias', r'aunts'),
                (r'el primo', r'male counsin'),
                (r'la prima', r'female counsin'),
                (r'los primos', r'the counsins'),
                (r'las primas', r'only girl counsins'),
                (r'los ni\~nos', r'the children'),
                (r'el hermano', r'the brother'),
                (r'la hermana', r'the sister'),
                (r'el hermanastro', r'step brother'),
                (r'la hermanastra', r'step sister'),
                (r'el hijo \'unica', r'the only son'),
                (r'la hija \'unica', r'the only daughter'),
                (r'casado', r'married (male)'),
                (r'casada', r'married (female)'),
                (r'divorciado', r'divorced (male)'),
                (r'divorciada', r'divorced (female)'),
                (r'el nieto', r'the grandson'),
                (r'la nieta', r'the granddaughter'),
            ]
        },  # a section object
        {
            'title': 'Talking about my family',
            'exercises': [
                (r'Tengo', r'I have'),
                (r'No', r'(I) do not (have)'),
                (r'Se llama', r'(He/She) is called'),
                (r'Se llaman', r'(They are) called'),
                (r'el/un', r'the/a (singlular nouns, musculine)'),
                (r'la/una', r'the/a (sigular nouns, feminine)'),
                (r'los/unos', r'the/some (plural nouns masculine and feminine)'),
                (r'las/unas', r'the/some (plural nouns feminine only)'),
                (r'unas frases sobre la familia', r'some phrases about the family'),
                (r'El t\'io se llama Ted', r'The uncle is called Ted'),
                (r'Tengo un hermano', r'I have a brother'),
                (r'No tengo una hermana', r'I do not have a sister'),
                (r'Los abuelos se llaman Fred y Phil', r'The grandfathers are called Fred and Phil'),
                (r'!`Hola! Tengo un hermano pero no tengo hermanas', r'Hello! I have a brother but I do not have sisters'),
                (r'Soy', r'I am'),
                (r'de', r'of/from'),
                (r'ma\'s largas', r'longer'),
                (r'El hermano de mi madre es mi t\'io', 'My mother\'s brother is my uncle'),
                (r'Los padres de mi padre son mis abuelos', 'My father\'s parents are my grandparents'),
            ]
        }, # a section object
        {
            'title': 'Numbers 11-31',
            'exercises': [
                (r'once', r'11'),
                (r'doce', r'12'),
                (r'trece', r'13'),
                (r'catorce', r'14'),
                (r'quince', r'15'),
                (r'diecis\'eis', r'16'),
                (r'diecisiete', r'17'),
                (r'dieciocho', r'18'),
                (r'diecinueve', r'19'),
                (r'veinte', r'20'),
                (r'veinteuno', r'21'),
                (r'veinted\'os', r'22'),
                (r'veintitr\'es', r'23'),
                (r'veinticuatro', r'24'),
                (r'veinticinco', r'25'),
                (r'veintis\'eis', r'26'),
                (r'veintisiete', r'27'),
                (r'veintiocho', r'28'),
                (r'veintinueve', r'29'),
                (r'treinta', r'30'),
                (r'treinta y uno', r'31')
            ]
        }, # a section object
        {
            'title': 'Mi Vida Loca',
            'exercises': [
                (r'loca', r'crazy'),
                (r'vida', r'life'),
                (r'tambi\'en', r'also'),
                (r'perd\'on', r'excuse me'),
                (r'gracias', r'thank you'),
                (r'adi\'os', r'good bye'),
                (r'hola', r'hello'),
                (r'?`C\'omo se llama...?', r'What is the name of ...?'),
                (r'?`C\'omo te llamas?', r'What is your name?'),
                (r'la calle', r'the street'),
                (r'eres', r'are you (?)'),
                (r'De nada', r'You are welcome'),
                (r'No entiendo', r'I do not understand'),
                (r'entiendo', r'I get it'),
                (r'El amiga/amigo', r'the friend'),
                (r's\'i', r'yes'),
                (r'si', r'if'),
                (r'nunca', r'never'),
                (r'un piso', r'a flat'),
                (r'dormitorio', r'bedroom'),
                (r'salir', r'to go out / to leave'),
                (r'quiero', r'I want'),
                (r'un cafe', r'a coffee'),
                (r'con leche', r'with milk'),
                (r'una tostada', r'a piece of toast'),
                (r'fr\'io', r'cold'),
                (r'fr\'ia', r'cool'),
                (r'cerveza', r'beer'),
                (r'caliente', r'warm/hot')
            ]
        },  # a section object
        {
            'title': 'Los meses',
            'exercises': [
                (r'meses', r'months'),
                (r'enero', r'January'),
                (r'febrero', r'February'),
                (r'marco', r'March'),
                (r'abril', r'April'),
                (r'mayo', r'May'),
                (r'junio', r'June'),
                (r'julio', r'July'),
                (r'agosto', r'August'),
                (r'septiembre/setiembre', r'September'),
                (r'octubre', r'October'),
                (r'noviembre', r'November'),
                (r'diciembre', r'December'),
                (r'Feliz cumplean\~os', r'Happy birthday')
            ]
        },
    ]
}

'''
contents of ZOOM espanol 1
'''
ZOOM_ESPANOL_1 = {
    'title': 'Zoom Espanol 1',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections': [
        {
            'title': 'O Me presento',
            'exercises': [
                (r'!`Hola!', r'Hello!'),
                (r'Saludos', r'Greetings'),
                (r'Adi\'os', r'Goodbye'),
                (r'Hasta luego', r'See you later'),
                (r'Hasta pronto', r'See you soon'),
                (r'Soy ana', 'I am Ana'),
                ('Me llamo Federico', 'My name is Federico'),
                ('escucha', 'listen'),
                ('repite', 'repeat'),
                ('habla', 'speak'),
                ('lee', 'read'),
                ('escribe', 'write'),
                ('pregunta', 'ask'),
                ('indica', 'point to'),
                ('contesta', 'answer'),
                ('mira', 'look'),
                ('empareja', 'match'),
                (r'?`C\'omo te llamas?', 'What\'s your name?'),
                ('Se llama Olivia', 'Her name is Olivia'),
                (r'?`Qu\'e tal?', 'How are you?'),
                (r'Buenos d\'ias', 'Good morning'),
                ('Buenas tardes', 'Good afternoon'),
                ('Buenas noches', 'Good night'),
                ('uno', 'one'),
                ('dos', 'two'),
                ('tres', 'three'),
                ('cuatro', 'four'),
                ('cinco', 'five'),
                ('seis', 'six'),
                ('siete', 'seven'),
                ('ocho', 'eight'),
                ('nueve', 'nine'),
                ('diez', 'ten'),
                ('once', 'eleven'),
                ('doce', 'twelve'),
                ('trece', 'thirteen'),
                ('catorce', 'fourteen'),
                ('quince', 'fifteen'),
                (r'diecis\'eis', 'sixteen'),
                ('diecisiete', 'seventeen'),
                ('dieciocho', 'eighteen'),
                ('diecinueve', 'nineteen'),
                ('veinte', 'twenty'),
                ('el abuelo', 'grandfather'),
                ('la abuela', 'grandmother'),
                ('los abuelos', 'grandparents'),
                ('mi padre', 'my father'),
                ('mi madre', 'my mother'),
                ('mis padres', 'my parents'),
                ('el hermano', 'brother'),
                ('la hermana', 'sister'),
                (r'el t\'io', 'uncle'),
                (r'la t\'ia', 'aunt'),
                ('el primo', 'cousin(m)'),
                ('el prima', 'cousin(f)'),
                ('el hermanastro', 'stepbrother'),
                ('la hermanastra', 'stepsister'),
                ('el padrastro', 'stepfather'),
                ('la madrastra', 'stepmother'),
                (r'Soy hijo \'unico', 'I am an only child (m)'),
                (r'Soy hija \'unica', 'I am an only child (f)'),
                ('la familia', 'the family'),
                (r'?`Cu\'antos a\~nos tienes?', 'How old are you?'),
                (r'Tengo X a\~nos', 'I am X years old'),
                ('treinta', 'thirty'),
                ('cuarenta', 'forty'),
                ('cincuenta', 'fifty'),
                ('sesenta', 'sixty'),
                ('setenta', 'seventy'),
                ('ochenta', 'eightly'),
                ('noventa', 'ninety'),
                ('cien', 'a hundred'),
                (r'gente y n\'umeros', 'people and numbers'),
                ('hay', 'there is, there are'),
                ('no hay', 'there is not, there are not'),
                ('ser', 'to be'),
                ('tener', 'to have'),
                ('llamarse', 'to be called')
            ]
        },  # a section object
        {
            'title': '1A Me describo',
            'exercises': [
                (r'Cumplea\~nos y fiestas', 'birthdays and festivals'),
                (r'enero', r'January'),
                (r'febrero', r'February'),
                (r'marco', r'March'),
                (r'abril', r'April'),
                (r'mayo', r'May'),
                (r'junio', r'June'),
                (r'julio', r'July'),
                (r'agosto', r'August'),
                (r'septiembre/setiembre', r'September'),
                (r'octubre', r'October'),
                (r'noviembre', r'November'),
                (r'diciembre', r'December'),
                ('lunes', 'Monday'),
                ('martes', 'Tuesday'),
                (r'mi\'ercoles', 'Wednesday'),
                ('jueves', 'Thursday'),
                ('viernes', 'Friday'),
                (r's\'abado', 'Saturday'),
                ('domingo', 'Sunday'),
                ('mis mascotas', 'my pets'),
                (r'un rat\'on', 'a mouse'),
                (r'un p\'ajaro', 'a bird'),
                ('un gato', 'a cat'),
                ('una rata', 'a rat'),
                ('una tortuga', 'a turtle / tortoise'),
                ('un perro', 'a dog'),
                (r'rua ara\~na', 'a spider'),
                ('un pez', 'a fish'),
                ('un conejo', 'a rabbit'),
                ('un caballo', 'a horse'),
                ('una cobaya', 'a guinea pig'),
                ('una serpiente', 'a snake'),
                ('blanco/a', 'white'),
                ('negro/a', 'black'),
                ('rojo/a', 'red'),
                ('azul', 'blue'),
                ('verde', 'green'),
                ('amarillo/a', 'yellow'),
                ('naranja', 'orange'),
                ('gris', 'grey'),
                (r'marr\'on', 'brown'),
                ('rosa', 'pink'),
                ('morado/a', 'purple'),
                ('lenguas y nacionalidades', 'languages and nationalities'),
                (r'ingl\'es / inglesa', 'English'),
                (r'escoc\'es / escocesa', 'Scottish'),
                (r'irland\'es / irlandesa', 'Irish'),
                (r'gal\'es / galesa', 'Welsh'),
                (r'franc\'es / francesa', 'French'),
                (r'espa\~nol(a)', 'Spanish'),
                (r'portugu\'es / portuguesa', 'Portuguese'),
                ('italiano/a', 'Italian'),
                (r'?`C\'omo eres?', 'What are you like?'),
                ('Tengo...', 'I have...'),
                ('el pelo', 'hair'),
                ('largo', 'long'),
                ('corto', 'short'),
                ('liso', 'straight'),
                ('rizado', 'curly'),
                ('ondulado', 'wavy'),
                ('de punta', 'spiky'),
                ('los ojos', 'eyes'),
                ('bigote', 'moustache'),
                ('barba', 'beard'),
                ('pecas', 'freckles'),
                ('Llevo gafas', 'I wear glasses'),
                ('Soy...', 'I am...'),
                ('alto/a', 'tall'),
                ('bajo/a', 'short'),
                ('delgado/a', 'slim'),
                ('gordo/a', 'fat'),
                ('de talla mediana', 'medium size'),
                ('ordenado/a', 'tidy'),
                ('desordenado/a', 'untidy'),
                (r'simp\'atico/a', 'friendly'),
                (r'antip\'atico/a', 'unfriendly'),
                ('paciente', 'patient'),
                ('impaciente', 'impatient'),
                ('estudioso/a', 'studious'),
                ('perezoso/a', 'lazy'),
                ('testarudo/a', 'stubborn'),
                ('extrovertido/a', 'outgoing'),
                (r't\'imido/a', 'shy'),
                ('inteligente', 'intelligent'),
                ('bobo/a', 'silly'),
                ('maduro/a', 'mature'),
                ('inmaduro/a', 'immature'),
                ('el chico', 'the boy'),
                ('la chica', 'the girl'),
                ('alguien', 'someone'),
                ('un poco', 'a little'),
                ('bastante', 'quite'),
                ('muy', 'very'),
                ('demasiado', 'too'),
                ('y', 'and'),
                ('pero', 'but'),
                (r'tambi\'en', 'also'),
                ('sin embargo', 'however'),
                ('casa', 'home')
            ]
        }, # a section object
        {
            'title': '1B El insti',
            'exercises': [
                (r'la educaci\'on f\'isica', 'PE'),
                (r'el espa\~nol', 'Spanish'),
                (r'el ingl\'es', 'English'),
                (r'la geograf\'ia', 'geography'),
                ('la historia', 'history'),
                (r'la informa\'atica', 'ICT'),
                (r'la tecnolog\'ia', 'design and technology'),
                (r'las ciencias', 'science'),
                (r'las matem\'aticas', 'mathematics'),
                (r'f\'acil', 'easy'),
                (r'diff\'icil', 'difficult'),
                (r'\'util', 'useful'),
                ('aburrido/a', 'boring'),
                ('divertido/a', 'fun, amusing'),
                ('interesante', 'interesting'),
                ('un poco', 'a little'),
                ('bastante', 'fairly, quite'),
                ('tan', 'so'),
                ('muy', 'very'),
                ('demasiado', 'too (much)'),
                (r'para m\'i', 'for me'),
                ('pero', 'but'),
                ('me gusta', 'I like'),
                ('te gusta', 'you like'),
                ('correcto', 'true'),
                ('mentira', 'false'),
                ('la hora y el horario', 'time and timetable'),
                ('Es la una', 'It is one o\'clock'),
                ('... y cinco', '... five past one'),
                ('... y cuarto', '... a quarter past one'),
                ('... y veinte', '... twenty past one'),
                ('... y media', '... half past one'),
                ('Son las dos', 'It is two o\'clock'),
                ('... menos venticinco', '... twenty-five to two'),
                ('... menos cuarto', '... a quarter to two'),
                ('... menos diez', '... ten to two'),
                (r'Es el mediodi\'a', 'It is midday'),
                ('Es la medianoche', 'It is midnight'),
                ('las instalaciones', 'school buildings'),
                ('el aula', 'the classroom'),
                ('el gimnasio', 'the gym'),
                ('el laboratorio', 'the laboratory'),
                ('el patio', 'the playground'),
                ('la biblioteca', 'the library'),
                ('la oficina', 'the office'),
                ('la oficina del director', 'the headteather\'s office'),
                ('grande', 'large'),
                (r'peque\~no/a', 'small'),
                ('moderno/a', 'modern'),
                ('antiguo/a', 'old'),
                ('bonito/a', 'attractive'),
                ('feo/a', 'ugly'),
                (r'c\'omodo/a', 'comfortable'),
                ('hay', 'there is / there are'),
                ('leer un libro', 'to read a book'),
                ('comer un bocadillo', 'to eat a sandwich'),
                ('estudiar ciencias', 'to study science'),
                ('charlar con amigos', 'to chat with friends'),
                ('practicar deporte', 'to play sport'),
                ('escribir cartas', 'to write letters'),
                ('la ropa', 'clothes'),
                ('llevar', 'to wear'),
                ('un jersey', 'a jersey'),
                ('una camisa', 'a shirt'),
                ('una camiseta', 'a blouse'),
                ('una corbata', 'a tie'),
                ('una falda', 'a skirt'),
                ('una sudadera', 'a sweatshirt'),
                ('unas zapatillas', 'trainers'),
                ('unos calcetines', 'socks'),
                ('unos pantalones', 'trousers'),
                ('unos vaqueros', 'jeans'),
                ('unos zapatos', 'shoes'),
                (r'inc\'omodo/a', 'uncomfortable'),
                ('elegante', 'stylish'),
                (r'pr\'actico/a', 'practical'),
                ('formal', 'formal'),
                (r'rid\'iculo/a', 'ridiculous'),
                ('informal', 'informal')
            ]
        }, # a section object
    ]
}
