# -*- coding: utf-8 -*-
# pylint: disable=C0301


'''
contents from tutor
'''
TUTOR = {
    'title': 'Tutor Year8',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections': [
        {
            'title': 'Vocabulary',
            'exercises': [
                ('cabeza', 'head'),
                ('codo', 'elbow'),
                ('boca', 'mouth'),
                ('oreja/oido', 'ears'),
                ('cuello', 'neck'),
                ('espalda', 'back'),
                ('pecho', 'chest'),
                ('tobillo', 'ankle'),
                ('hombro', 'shoulders'),
                ('dientes', 'teeth'),
                ('uñas', 'nail'),
                ('huesos', 'bones'),
                ('sangre', 'blood'),
                ('labios', 'lips'),
                ('músculos', 'muscles'),
                ('lengua', 'tongue'),
                ('Se encuentra bien.', 'He feels well'),
                ('Le duela la cabeza', 'He has a headache'),
                ('Está mareada', 'She is dizzy'),
                ('cita', 'appointment'),
                ('médico', 'doctor'),
                ('urgencias', 'emergency department'),
                ('tarjeta sanitaria', 'insurance card'),
                ('gripe', 'flu'),
                ('quedar', 'to meet someone you already know'),
                ('puerta', 'door'),
                ('creo', 'I think'),
                ('no sé', 'I don\'t know'),
                ('¿Puedo hacer algo?', 'Can I do anything?'),
                ('Ahora mismo', 'right now'),
                ('recoger', 'to pick up'),
                ('¡Pues, claro!', 'of course!'),
                ('dime', 'tell me'),
                ('manzana', 'apples'),
                ('verduras', 'vegetables'),
                ('tráer', 'to bring'),
                ('apuntar', 'to write down'),
                ('enfermo', 'sick'),
                ('resfriado', 'cold'),
                ('tos', 'cough'),
                ('mareado', 'dizzy'),
                ('garganta', 'neck'),
                ('analgésico', 'pain killer'),
                ('tensión', 'blood pressure'),
                ('jarabe', 'medicine'),
                ('pomada', 'cream'),
                ('termómetro', 'thermometer'),
                ('agua oxigenada', 'oxidised water'),
                ('venda', 'bandages'),
                ('colirio', 'eyedrops'),
                ('tirita', 'plaster'),
                ('jeringuilla', 'syringe'),
                ('alcohol', 'alcohol'),
                ('algodón', 'cotton'),
                ('esparadrapo', 'tape'),
                ('cápsulas', 'capsules'),
                ('gasa', 'gauze'),
                ('tijeraas', 'scissors'),
                ('pastillas', 'pills'),
            ]
        }
    ]
}

'''
contents from ISEB Spanish Vocabulary
'''
ISEB_SPANISH_VOCABULARY = {
    'title': 'ISEB Spanish Vocabulary',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections': [
        {
            'title': 'Language of the classroom and ICT',
            'exercises': [
                ('en mi cartera', 'in my school bag'),
                ('en mi mochila', 'in my rucksack'),
                ('el bolígrafo', 'pen, biro'),
                ('la cola', 'glue'),
                ('el compás', 'pair of compasses'),
                ('el cuaderno', 'exercise book'),
                ('el estuche', 'pencil case'),
                ('la goma', 'rubber'),
                ('el lápiz', 'pencil'),
                ('el libro (de texto)', '(text) book'),
                ('el papel', 'paper'),
                ('la regla', 'ruler'),
                ('el rotulador', 'felt-tip pen'),
                ('las tijeras', 'scissors'),
                ('la carpeta', 'folder'),
                ('el celo', 'adhesive tape'),
                ('el clip', 'paper clip'),
                ('la perforadora', 'hole punch'),
                ('la grapadora', 'stapler'),
                ('el sacapuntas', 'pencil sharpener'),
                ('la calculadora', 'calculator'),
                ('en el aula (f.)', 'in the classroom'),
                ('el armario', 'cupboard'),
                ('el atlas', 'atlas'),
                ('el cuadro', 'picture'),
                ('el estante', 'shelf'),
                ('la estantería', 'set of shelves'),
                ('el mapa (m.)', 'map'),
                ('el magnetofón', 'tape recorder'),
                ('la cinta', 'tape'),
                ('el cassette / el casete', 'cassette (player)'),
                ('la mesa del profesor', 'teacher\'s desk'),
                ('el ordenador', 'computer'),
                ('la pizarra', 'board'),
                ('el póster', 'poster'),
                ('el pupitre', 'pupil\'s desk'),
                ('la silla', 'chair'),
                ('la papelera', 'waste-paper bin'),
                ('el televisor', 'television set'),
                ('el vídeo', 'video'),
                ('el DVD', 'DVD'),
                ('el lector de DVDs', 'DVD player'),
                ('el CD, el disco compacto', 'CD'),
                ('el lector de CDs', 'CD player'),
                ('la librería', 'bookcase, bookshop'),
                ('la biblioteca', 'bookcase, library'),
                ('la pantalla', 'screen'),
                ('la pantalla táctil', 'touch screen'),
                ('el rotulador', 'marker pen'),
                ('la clase', 'lesson, class, classroom'),
                ('la página', 'page'),
                ('el ejercicio', 'exercise'),
                ('el trabajo', 'work'),
                ('los deberes', 'homework, prep'),
                ('el juego de rol', 'role play'),
                ('el examen', 'exam (ination)'),
                ('la pregunta', 'question'),
                ('la respuesta', 'answer'),
                ('el problema (m.)', 'problem'),
                ('el ejemplo', 'example'),
                ('la frase', 'sentence'),
                ('la asignatura', 'subject'),
                ('el curso', 'course, one school year'),
                ('el vocabulario', 'vocabulary'),
                ('las notas', 'marks'),
                ('el grupo', 'group'),
                ('la palabra', 'word'),
                ('el error', 'mistake'),
                ('el texto', 'text'),
                ('la carta', 'letter'),
                ('el anuncio', 'advertisement'),
                ('la afirmacioón', 'statement'),
                ('el dibujo', 'drawing'),
                ('la descripción', 'description'),
                ('el hueco', 'gap, blank space'),
                ('ausente', 'absent'),
                ('presente', 'present'),
                ('adecuado', 'suitable, appropriate'),
                ('decir', 'to say, to tell'),
                ('dibujar', 'to draw'),
                ('contestar', 'to answer'),
                ('saber', 'to know (a fact or how to...)'),
                ('durar', 'to last'),
                ('comenzar (ie) / empezar (ie)', 'to begin, to start'),
                ('terminar', 'to end, to finish'),
                ('añadir', 'to add'),
                ('indicar', 'to indicate'),
                ('emparejar', 'to pair up'),
                ('subrayar', 'to underline'),
                ('escoger', 'to choose'),
                ('rellenar', 'to fill in'),
                ('describir', 'to describe'),
                ('mencionar', 'to mention'),
                ('completar', 'to complete'),
                ('tener que', 'to have to'),
                ('venir', 'to come'),
                ('explicar', 'to explain'),
                ('copiar', 'to copy'),
                ('dar', 'to give'),
                ('buscar', 'to look for / to search'),
                ('encontrar (ue)', 'to find'),
                ('cortar', 'to cut'),
                ('pegar', 'to stick'),
                ('abrir', 'to open'),
                ('cerrar (ie)', 'to close'),
                ('olvidar', 'to forget'),
                ('perder (ie)', 'to lose'),
                ('ver', 'to see'),
                ('repartir', 'to give out'),
                ('recortar', 'to cut out'),
                ('compartir', 'to share'),
                ('poner una equis (en una casilla)', 'to put an X (in a box)'),
                ('corregir (i)', 'to correct'),
                ('poder (ue)', 'to be able to'),
                ('intentar', 'to try'),
                ('prestar', 'to lend'),
                ('pedir (i) prestado', 'to borrow'),
                ('el ordenador portátil', 'laptop'),
                ('el teclado', 'keyboard'),
                ('la tecla', 'key'),
                ('el ratón', 'mouse'),
                ('el botón', 'button'),
                ('el disco duro', 'hard drive'),
                ('el CD-ROM', 'CD-ROM'),
                ('el módem', 'modem'),
                ('la fuente', 'font'),
                ('el puerto', 'port'),
                ('Internet', 'Internet'),
                ('la página web', 'webpage'),
                ('el servidor', 'server'),
                ('la banda ancha', 'broadband'),
                ('el correo electrónico', 'email'),
                ('la dirección de correo electrónico', 'email address'),
                ('la cuenta de correo electróncio', 'email account'),
                ('la mensajería instantánea', 'instant messaging'),
                ('la red', 'the net, network'),
                ('el navegador', 'web browser'),
                ('la página inicial', 'home page'),
                ('(los) favoritos', 'bookmarks'),
                ('el sitio web', 'website'),
                ('el buscador', 'search engine'),
                ('la búsqueda', 'search (internet)'),
                ('el escritorio', 'desktop'),
                ('el programa (m.)', 'program'),
                ('el menú de inicio', 'start menu'),
                ('la hoja de cálculo', 'spreadsheet'),
                ('la base de datos', 'database'),
                ('el procesador de textos', 'word processor'),
                ('los accesorios', 'accessories'),
                ('la papelera de reciclaje', 'recycling bin'),
                ('la ventana', '(application\'s) window'),
                ('el icono', 'icon'),
                ('la carpeta', 'folder'),
                ('el documento', 'document'),
                ('el acceso directo / el atajo', 'shortcut'),
                ('el fichero / el archivo', 'file'),
                ('la ayuda', 'help (information)'),
                ('el (documento) adjunto', '(email) attachment'),
                ('el videojuego', 'computer/video game'),
                ('el software', 'software'),
                ('la impresora', 'printer'),
                ('el escáner', 'scanner'),
                ('el virus', 'virus'),
                ('el nombre de usuario', 'username'),
                ('la contraseña (de acceso) / la palabra de acceso', 'password'),
                ('la llave USB', 'USB key'),
                ('el cursor', 'cursor'),
                ('la plantilla', 'template'),
                ('la pestaña', 'tab'),
                ('el mensaje', 'message, email'),
                ('el protector de pantalla', 'screen protector'),
                ('el sonido', 'sound'),
                ('la letra mayúscula', 'capital letter'),
                ('la barra espaciadora', 'space bar'),
                ('la barra de menús', 'menu bar'),
                ('los gráficos', 'graphics'),
                ('la actualización', '(OS/software) update'),
                ('la copia de seguridad', 'backup'),
                ('el monitor', 'monitor'),
                ('arroba', 'at @'),
                ('punto com', 'dot com'),
                ('interactivo(a)', 'interactive'),
                ('inalámbrico(a)', 'wireless'),
                ('cursivo(a)', 'italic'),
                ('multimedia (adj. inv.)', 'multimedia'),
                ('raya', 'dash'),
                ('barra', 'slash'),
                ('compatible', 'compatible'),
                ('en línea', 'online'),
                ('casa', 'home'),
                ('el teléfono móvil', 'mobile phone'),
                ('el mensaje de texto', 'text message'),
                ('la cobertura', 'reception'),
                ('la webcam', 'webcam'),
                ('la cámara digital', 'digital camera'),
                ('grabar un CD', 'to burn a CD'),
                ('editar', 'to edit'),
                ('hacer clic / cliquear', 'to click'),
                ('copiar', 'to copy'),
                ('cortar', 'to cut'),
                ('pegar', 'to paste'),
                ('cancelar', 'to cancel'),
                ('abrir', 'to open'),
                ('cerrar (ie)', 'to close'),
                ('guardar', 'to save'),
                ('eliminar', 'to delete'),
                ('crear', 'to create'),
                ('escanear', 'to scan'),
                ('enviar', 'to send'),
                ('comprimir', 'to compress'),
                ('apagar', 'to shut down'),
                ('encender', 'to turn on'),
                ('reiniciar', 'to restart'),
                ('bajar / descargar', 'to download'),
                ('correr (un programa)', 'to run (a program)'),
                ('navegar por Internet', 'to surf the web'),
                ('cargar la batería', 'to charge the battery'),
                ('minimizar', 'to minimise'),
                ('maximizar', 'to maximise'),
                ('teclear', 'to type (in)'),
                ('avanzar', 'to scroll down'),
                ('salir de', 'to log out'),
                ('registrar', 'to register'),
                ('entrar en el sistema (m.)', 'to log in'),
                ('realzar / destacar', 'to highlight'),
                ('escapar', 'to escape'),
                ('ampliar', 'to enlarge'),
                ('digitalizar', 'to digitalise'),
                ('enviar un mensaje (de texto)', 'to text (message to)'),
            ]
        }
    ]
}
