# -*- coding: utf-8 -*-
# pylint: disable=C0301

'''
contents of Zhenglin's  Spanish year 7
'''
ZHENGLIN_YEAR7 = {
    'title': 'Spanish Year 7',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections':[
        {
            'title': 'Numbers 1 - 10',
            'exercises': [
                ('uno', '1'),
                ('dos', '2'),
                ('tres', '3'),
                ('cuatro', '4'),
                ('cinco', '5'),
                ('seis', '6'),
                ('sieta', '7'),
                ('ocho', '8'),
                ('nueve', '9'),
                ('diez', '10'),
                ('números', 'numbers')
            ]
        },  # a section object
        {
            'title': 'Family',
            'exercises': [
                ('En mi familia, hey...', 'In my family, there is/are...'),
                ('y', 'and'),
                ('mi', 'my (singular noun)'),
                ('mis', 'my (plural noun)'),
                ('los abuelos', 'grandparents'),
                ('el abuelo', 'grandfather'),
                ('la abuela', 'grandmother'),
                ('los padres', 'parents'),
                ('el padre', 'the father'),
                ('la madre', 'the mother'),
                ('el padrasto', 'step dad'),
                ('la madrastra', 'step mother'),
                ('el marido', 'husband'),
                ('la esposa??', 'wife'),
                ('los parientes', 'the relatives'),
                ('la tía', 'aunt'),
                ('el tío', 'uncle'),
                ('los tíos', 'uncles'),
                ('las tías', 'aunts'),
                ('el primo', 'male counsin'),
                ('la prima', 'female counsin'),
                ('los primos', 'the counsins'),
                ('las primas', 'only girl counsins'),
                ('los niños', 'the children'),
                ('el hermano', 'the brother'),
                ('la hermana', 'the sister'),
                ('el hermanastro', 'step brother'),
                ('la hermanastra', 'step sister'),
                ('el hijo única', 'the only son'),
                ('la hija única', 'the only daughter'),
                ('casado', 'married (male)'),
                ('casada', 'married (female)'),
                ('divorciado', 'divorced (male)'),
                ('divorciada', 'divorced (female)'),
                ('el nieto', 'the grandson'),
                ('la nieta', 'the granddaughter'),
            ]
        },  # a section object
        {
            'title': 'Talking about my family',
            'exercises': [
                ('Tengo', 'I have'),
                ('No', '(I) do not (have)'),
                ('Se llama', '(He/She) is called'),
                ('Se llaman', '(They are) called'),
                ('el/un', 'the/a (singlular nouns, musculine)'),
                ('la/una', 'the/a (sigular nouns, feminine)'),
                ('los/unos', 'the/some (plural nouns masculine and feminine)'),
                ('las/unas', 'the/some (plural nouns feminine only)'),
                ('unas frases sobre la familia', 'some phrases about the family'),
                ('El tío se llama Ted', 'The uncle is called Ted'),
                ('Tengo un hermano', 'I have a brother'),
                ('No tengo una hermana', 'I do not have a sister'),
                ('Los abuelos se llaman Fred y Phil', 'The grandfathers are called Fred and Phil'),
                ('¡Hola! Tengo un hermano pero no tengo hermanas', 'Hello! I have a brother but I do not have sisters'),
                ('Soy', 'I am'),
                ('de', 'of/from'),
                ('más largas', 'longer'),
                ('El hermano de mi madre es mi tío', 'My mother\'s brother is my uncle'),
                ('Los padres de mi padre son mis abuelos', 'My father\'s parents are my grandparents'),
            ]
        }, # a section object
        {
            'title': 'Numbers 11-31',
            'exercises': [
                ('once', '11'),
                ('doce', '12'),
                ('trece', '13'),
                ('catorce', '14'),
                ('quince', '15'),
                ('dieciséis', '16'),
                ('diecisiete', '17'),
                ('dieciocho', '18'),
                ('diecinueve', '19'),
                ('veinte', '20'),
                ('veinteuno', '21'),
                ('veintedós', '22'),
                ('veintitrés', '23'),
                ('veinticuatro', '24'),
                ('veinticinco', '25'),
                ('veintiséis', '26'),
                ('veintisiete', '27'),
                ('veintiocho', '28'),
                ('veintinueve', '29'),
                ('treinta', '30'),
                ('treinta y uno', '31')
            ]
        }, # a section object
        {
            'title': 'Mi Vida Loca',
            'exercises': [
                ('loca', 'crazy'),
                ('vida', 'life'),
                ('también', 'also'),
                ('perdón', 'excuse me'),
                ('gracias', 'thank you'),
                ('adiós', 'good bye'),
                ('hola', 'hello'),
                ('¿Cómo se llama...?', 'What is the name of ...?'),
                ('¿Cómo te llamas?', 'What is your name?'),
                ('la calle', 'the street'),
                ('eres', 'are you (?)'),
                ('De nada', 'You are welcome'),
                ('No entiendo', 'I do not understand'),
                ('entiendo', 'I get it'),
                ('El amiga/amigo', 'the friend'),
                ('sí', 'yes'),
                ('si', 'if'),
                ('nunca', 'never'),
                ('un piso', 'a flat'),
                ('dormitorio', 'bedroom'),
                ('salir', 'to go out / to leave'),
                ('quiero', 'I want'),
                ('un cafe', 'a coffee'),
                ('con leche', 'with milk'),
                ('una tostada', 'a piece of toast'),
                ('frío', 'cold'),
                ('fría', 'cool'),
                ('cerveza', 'beer'),
                ('caliente', 'warm/hot')
            ]
        },  # a section object
        {
            'title': 'Los meses',
            'exercises': [
                ('meses', 'months'),
                ('enero', 'January'),
                ('febrero', 'February'),
                ('marzo', 'March'),
                ('abril', 'April'),
                ('mayo', 'May'),
                ('junio', 'June'),
                ('julio', 'July'),
                ('agosto', 'August'),
                ('septiembre/setiembre', 'September'),
                ('octubre', 'October'),
                ('noviembre', 'November'),
                ('diciembre', 'December'),
                ('Feliz Cumpleaños', 'Happy birthday')
            ]
        },
    ]
}

'''
contents of ZOOM espanol 1
'''
ZOOM_ESPANOL_1 = {
    'title': 'Zoom Espanol 1',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections': [
        {
            'title': 'O Me presento',
            'exercises': [
                ('¡Hola!', 'Hello!'),
                ('Saludos', 'Greetings'),
                ('Adiós', 'Goodbye'),
                ('Hasta luego', 'See you later'),
                ('Hasta pronto', 'See you soon'),
                ('Soy ana', 'I am Ana'),
                ('Me llamo Federico', 'My name is Federico'),
                ('escucha', 'listen'),
                ('repite', 'repeat'),
                ('habla', 'speak'),
                ('lee', 'read'),
                ('escribe', 'write'),
                ('pregunta', 'ask'),
                ('indica', 'point to'),
                ('contesta', 'answer'),
                ('mira', 'look'),
                ('empareja', 'match'),
                ('¿Cómo te llamas?', 'What\'s your name?'),
                ('Se llama Olivia', 'Her name is Olivia'),
                ('¿Qué tal?', 'How are you?'),
                ('Buenos días', 'Good morning'),
                ('Buenas tardes', 'Good afternoon'),
                ('Buenas noches', 'Good night'),
                ('uno', 'one'),
                ('dos', 'two'),
                ('tres', 'three'),
                ('cuatro', 'four'),
                ('cinco', 'five'),
                ('seis', 'six'),
                ('siete', 'seven'),
                ('ocho', 'eight'),
                ('nueve', 'nine'),
                ('diez', 'ten'),
                ('once', 'eleven'),
                ('doce', 'twelve'),
                ('trece', 'thirteen'),
                ('catorce', 'fourteen'),
                ('quince', 'fifteen'),
                ('dieciséis', 'sixteen'),
                ('diecisiete', 'seventeen'),
                ('dieciocho', 'eighteen'),
                ('diecinueve', 'nineteen'),
                ('veinte', 'twenty'),
                ('el abuelo', 'grandfather'),
                ('la abuela', 'grandmother'),
                ('los abuelos', 'grandparents'),
                ('mi padre', 'my father'),
                ('mi madre', 'my mother'),
                ('mis padres', 'my parents'),
                ('el hermano', 'brother'),
                ('la hermana', 'sister'),
                ('el tío', 'uncle'),
                ('la tía', 'aunt'),
                ('el primo', 'cousin(m)'),
                ('la prima', 'cousin(f)'),
                ('el hermanastro', 'stepbrother'),
                ('la hermanastra', 'stepsister'),
                ('el padrastro', 'stepfather'),
                ('la madrastra', 'stepmother'),
                ('Soy hijo único', 'I am an only child (m)'),
                ('Soy hija única', 'I am an only child (f)'),
                ('la familia', 'the family'),
                ('¿Cuántos años tienes?', 'How old are you?'),
                ('Tengo X años', 'I am X years old'),
                ('treinta', 'thirty'),
                ('cuarenta', 'forty'),
                ('cincuenta', 'fifty'),
                ('sesenta', 'sixty'),
                ('setenta', 'seventy'),
                ('ochenta', 'eightly'),
                ('noventa', 'ninety'),
                ('cien', 'a hundred'),
                ('gente y números', 'people and numbers'),
                ('hay', 'there is, there are'),
                ('no hay', 'there is not, there are not'),
                ('ser', 'to be'),
                ('tener', 'to have'),
                ('llamarse', 'to be called')
            ]
        },  # a section object
        {
            'title': '1A Me describo',
            'exercises': [
                ('Cumpleaños y fiestas', 'birthdays and festivals'),
                ('enero', 'January'),
                ('febrero', 'February'),
                ('marco', 'March'),
                ('abril', 'April'),
                ('mayo', 'May'),
                ('junio', 'June'),
                ('julio', 'July'),
                ('agosto', 'August'),
                ('septiembre/setiembre', 'September'),
                ('octubre', 'October'),
                ('noviembre', 'November'),
                ('diciembre', 'December'),
                ('lunes', 'Monday'),
                ('martes', 'Tuesday'),
                ('miércoles', 'Wednesday'),
                ('jueves', 'Thursday'),
                ('viernes', 'Friday'),
                ('sábado', 'Saturday'),
                ('domingo', 'Sunday'),
                ('mis mascotas', 'my pets'),
                ('un ratón', 'a mouse'),
                ('un pájaro', 'a bird'),
                ('un gato', 'a cat'),
                ('una rata', 'a rat'),
                ('una tortuga', 'a turtle / tortoise'),
                ('un perro', 'a dog'),
                ('una araña', 'a spider'),
                ('un pez', 'a fish'),
                ('un conejo', 'a rabbit'),
                ('un caballo', 'a horse'),
                ('una cobaya', 'a guinea pig'),
                ('una serpiente', 'a snake'),
                ('blanco/a', 'white'),
                ('negro/a', 'black'),
                ('rojo/a', 'red'),
                ('azul', 'blue'),
                ('verde', 'green'),
                ('amarillo/a', 'yellow'),
                ('naranja', 'orange'),
                ('gris', 'grey'),
                ('marrón', 'brown'),
                ('rosa', 'pink'),
                ('morado/a', 'purple'),
                ('lenguas y nacionalidades', 'languages and nationalities'),
                ('inglés / inglesa', 'English'),
                ('escocés / escocesa', 'Scottish'),
                ('irlandés / irlandesa', 'Irish'),
                ('galés / galesa', 'Welsh'),
                ('francés / francesa', 'French'),
                ('español(a)', 'Spanish'),
                ('portugués / portuguesa', 'Portuguese'),
                ('italiano/a', 'Italian'),
                ('¿Cómo eres?', 'What are you like?'),
                ('Tengo...', 'I have...'),
                ('el pelo', 'hair'),
                ('largo', 'long'),
                ('corto', 'short'),
                ('liso', 'straight'),
                ('rizado', 'curly'),
                ('ondulado', 'wavy'),
                ('de punta', 'spiky'),
                ('los ojos', 'eyes'),
                ('bigote', 'moustache'),
                ('barba', 'beard'),
                ('pecas', 'freckles'),
                ('Llevo gafas', 'I wear glasses'),
                ('Soy...', 'I am...'),
                ('alto/a', 'tall'),
                ('bajo/a', 'short'),
                ('delgado/a', 'slim'),
                ('gordo/a', 'fat'),
                ('de talla mediana', 'medium size'),
                ('ordenado/a', 'tidy'),
                ('desordenado/a', 'untidy'),
                ('simpático/a', 'friendly'),
                ('antipático/a', 'unfriendly'),
                ('paciente', 'patient'),
                ('impaciente', 'impatient'),
                ('estudioso/a', 'studious'),
                ('perezoso/a', 'lazy'),
                ('testarudo/a', 'stubborn'),
                ('extrovertido/a', 'outgoing'),
                ('tímido/a', 'shy'),
                ('inteligente', 'intelligent'),
                ('bobo/a', 'silly'),
                ('maduro/a', 'mature'),
                ('inmaduro/a', 'immature'),
                ('el chico', 'the boy'),
                ('la chica', 'the girl'),
                ('alguien', 'someone'),
                ('un poco', 'a little'),
                ('bastante', 'quite'),
                ('muy', 'very'),
                ('demasiado', 'too'),
                ('y', 'and'),
                ('pero', 'but'),
                ('también', 'also'),
                ('sin embargo', 'however'),
                ('casa', 'home')
            ]
        }, # a section object
        {
            'title': '1B El insti',
            'exercises': [
                ('la educación física', 'PE'),
                ('el español', 'Spanish'),
                ('el inglés', 'English'),
                ('la geografía', 'geography'),
                ('la historia', 'history'),
                ('la informática', 'ICT'),
                ('la tecnología', 'design and technology'),
                ('las ciencias', 'science'),
                ('las matemáticas', 'mathematics'),
                ('fácil', 'easy'),
                ('diffícil', 'difficult'),
                ('útil', 'useful'),
                ('aburrido/a', 'boring'),
                ('divertido/a', 'fun, amusing'),
                ('interesante', 'interesting'),
                ('un poco', 'a little'),
                ('bastante', 'fairly, quite'),
                ('tan', 'so'),
                ('muy', 'very'),
                ('demasiado', 'too (much)'),
                ('para mí', 'for me'),
                ('pero', 'but'),
                ('me gusta', 'I like'),
                ('te gusta', 'you like'),
                ('correcto', 'true'),
                ('mentira', 'false'),
                ('la hora y el horario', 'time and timetable'),
                ('Es la una', 'It is one o\'clock'),
                ('... y cinco', '... five past one'),
                ('... y cuarto', '... a quarter past one'),
                ('... y veinte', '... twenty past one'),
                ('... y media', '... half past one'),
                ('Son las dos', 'It is two o\'clock'),
                ('... menos venticinco', '... twenty-five to two'),
                ('... menos cuarto', '... a quarter to two'),
                ('... menos diez', '... ten to two'),
                ('Es el mediodiá', 'It is midday'),
                ('Es la medianoche', 'It is midnight'),
                ('las instalaciones', 'school buildings'),
                ('el aula', 'the classroom'),
                ('el gimnasio', 'the gym'),
                ('el laboratorio', 'the laboratory'),
                ('el patio', 'the playground'),
                ('la biblioteca', 'the library'),
                ('la oficina', 'the office'),
                ('la oficina del director', 'the headteather\'s office'),
                ('grande', 'large'),
                ('pequeño/a', 'small'),
                ('moderno/a', 'modern'),
                ('antiguo/a', 'old'),
                ('bonito/a', 'attractive'),
                ('feo/a', 'ugly'),
                ('cómodo/a', 'comfortable'),
                ('hay', 'there is / there are'),
                ('leer un libro', 'to read a book'),
                ('comer un bocadillo', 'to eat a sandwich'),
                ('estudiar ciencias', 'to study science'),
                ('charlar con amigos', 'to chat with friends'),
                ('practicar deporte', 'to play sport'),
                ('escribir cartas', 'to write letters'),
                ('la ropa', 'clothes'),
                ('llevar', 'to wear'),
                ('un jersey', 'a jersey'),
                ('una camisa', 'a shirt'),
                ('una camiseta', 'a blouse'),
                ('una corbata', 'a tie'),
                ('una falda', 'a skirt'),
                ('una sudadera', 'a sweatshirt'),
                ('unas zapatillas', 'trainers'),
                ('unos calcetines', 'socks'),
                ('unos pantalones', 'trousers'),
                ('unos vaqueros', 'jeans'),
                ('unos zapatos', 'shoes'),
                ('incómodo/a', 'uncomfortable'),
                ('elegante', 'stylish'),
                ('práctico/a', 'practical'),
                ('formal', 'formal'),
                ('ridículo/a', 'ridiculous'),
                ('informal', 'informal')
            ]
        }, # a section object
        {
            'title': '2A Mi semana',
            'exercises': [
                ('el tiempo', 'the weather'),
                ('hace buen tiempo', 'it is fine / it is a nice day'),
                ('hace mal tiemo', 'it is bad weather / it is not a nice day'),
                ('hace sol', 'it is sunny'),
                ('hace calor', 'it is hot'),
                ('hace frío', 'it is cold'),
                ('hace viento', 'it is windy'),
                ('hay tormenta', 'it is stormy'),
                ('hay niebla', 'it is foggy'),
                ('hay nubes', 'it is cloudy'),
                ('llueve', 'it is raining'),
                ('nieva', 'it is snowing'),
                ('la primavera', 'spring'),
                ('el verano', 'summer'),
                ('el otoño', 'autumn'),
                ('el invierno', 'winter'),
                ('jugar a / al / a la', 'to play'),
                ('el fútbol', 'football'),
                ('el baloncesto', 'basketball'),
                ('el ciclismo', 'cycling'),
                ('el atletismo', 'athletics'),
                ('el boxeo', 'boxing'),
                ('la pelota vasca', 'pelota'),
                ('el voleibol', 'volleyball'),
                ('tiempo libre', 'free time'),
                ('ver la tele', 'to watch TV'),
                ('salir con amigos', 'to go out with friends'),
                ('tocar la guitarra', 'to play the guitar'),
                ('ir al cine', 'to go to the cinema'),
                ('montar a caballo', 'to ride a horse'),
                ('bailar en la disco', 'to dance in a disco'),
                ('jugar al ajedrez', 'to play chess'),
                ('jugar con videojuegos', 'to play computer games'),
                ('me apasiona', 'I love'),
                ('me aburre', 'it is boring'),
                ('me molesta', 'it annoys me'),
                ('me fastidia', 'it gets on my nerves'),
                ('navegar por internet', 'to surf the net'),
                ('poder', 'to be able'),
                ('preferir', 'to prefer'),
                ('prefiero', 'I prefer'),
                ('querer', 'to like / want'),
                ('si', 'if'),
                ('sí', 'yes'),
                ('por la mañana', 'in the morning'),
                ('levantarse', 'to get up'),
                ('lavarse', 'to get washed'),
                ('me lavo (los dientes)', 'I clean (my teeth)'),
                ('ducharse', 'to have a shower'),
                ('cepillarse', 'to brush'),
                ('me cepillo (el pelo)', 'I brush my hair'),
                ('peinarse', 'to comb / do hair'),
                ('ponerse', 'to put on (clothes)'),
                ('desayunar', 'to have breakfast'),
                ('despertarse', 'to wake up'),
                ('vestirse', 'to dress'),
                ('almorzar(ue)', 'to have lunch'),
                ('por la tarde', 'in the afternoon'),
                ('a las trece horas', 'at 13:00 hours'),
                ('descansar', 'to relax'),
                ('merendar(ie)', 'to have a snack'),
                ('pasear al perro', 'to walk the dog'),
                ('hacer los deberes', 'to do homework'),
                ('cenar', 'to have suppe'),
                ('acostarse(ue)', 'to go to bed'),
                ('dormirse(ue)', 'to fall asleep'),
                ('ir', 'to go'),
                ('hacer compras', 'to do the shopping'),
                ('la piscina', 'swimming pool'),
                ('nadar', 'to swim'),
                ('el fin de semana', '(at) the weekend'),
                ('hasta las diez', 'until ten oclock'),
                ('tarde', 'late'),
                ('temprano', 'early'),
                ('de acuerdo', 'agreed'),
                ('montar en bicicleta', 'to ride a bike'),
                ('el sábado', 'on Saturday'),
                ('los sábados', 'on Saturdays'),
                ('la cocina', 'kitchen'),
                ('las tostadas', 'toast'),
                ('los cereales', 'cereal'),
                ('en tren', 'by train'),
                ('frente a', 'opposite'),
                ('el mar', 'the sea'),
                ('pasarlo bomba', 'to have a great time')
            ]
        }, # a section object
        {
            'title': '2B Donde vivo yo',
            'exercises': [
                ('Vivo en ...', 'I live in ...'),
                ('Está en ...', 'It is in ...'),
                ('la montaña', 'the mountains'),
                ('la costa', 'the coast'),
                ('el campo', 'the countryside'),
                ('la ciudad', 'the city'),
                ('un pueblo', 'a town'),
                ('una aldea', 'a village'),
                ('un barrio', 'a neighbourhood'),
                ('las afueras', 'the outskirts'),
                ('¿Dónde está?', 'Where is it?'),
                ('siempre', 'always'),
                ('todos los días', 'every day'),
                ('a menudo', 'often'),
                ('a veces', 'sometimes'),
                ('nunca', 'never'),
                ('una vez a la semana', 'once a week'),
                ('dos veces a la semana', 'twice a week'),
                ('un supermercado', 'a supermarket'),
                ('un parque', 'a park'),
                ('una estación', 'a station'),
                ('un banco', 'a bank'),
                ('un museo', 'a museum'),
                ('una catedral', 'a cathedral'),
                ('un zoo', 'a zoo'),
                ('un colegio', 'a school'),
                ('un cine', 'a cinema'),
                ('un parque de atracciones', 'a theme park'),
                ('la bolera', 'the bowling alley'),
                ('el polideportivo', 'the sports centre'),
                ('la piscina', 'the swimming pool'),
                ('la oficina de Correos', 'the post office'),
                ('el ayuntamiento', 'the town hall'),
                ('la iglesia', 'the church'),
                ('los grandes almacenes', 'the department store'),
                ('la parada de autobús', 'the bus stop'),
                ('las tiendas', 'the shops'),
                ('Sigue/Siga', 'Carry on'),
                ('Todo recto', 'Straight ahead'),
                ('Tuerce/Tuerza', 'Turn'),
                ('Cruza/Cruce', 'Cross'),
                ('Toma/Tome', 'Take'),
                ('el puente', 'the bridge'),
                ('la primera/segunda/tercera', 'the first/second/thrid'),
                ('la calle', 'the street'),
                ('a la derecha', 'on the right'),
                ('a la izquierda', 'on the left'),
                ('Mi casa', 'My house'),
                ('un sótano', 'a basement'),
                ('la planta baja', 'the ground floor'),
                ('la primera planta', 'the first floor'),
                ('el ático', 'the attic'),
                ('una entrada', 'an entrance hall'),
                ('las escaleras', 'the stairs'),
                ('una cocina', 'a kitchen'),
                ('un salón', 'a living room'),
                ('un comedor', 'a dining room'),
                ('un dormitorio', 'a bedroom'),
                ('un cuarto de baño', 'a bathroom'),
                ('una ducha', 'a shower'),
                ('un aseo', 'a toilet'),
                ('un despacho', 'an office'),
                ('un jardín', 'a garden'),
                ('un balcón', 'a balcony'),
                ('una piscina', 'a swimming pool'),
                ('Mi dormitorio', 'My bedroom'),
                ('un armario', 'a wardrobe'),
                ('una cama', 'a bed'),
                ('un escritorio', 'a desk'),
                ('unas estanterías', 'a bookcase / some shelves'),
                ('una mestia de noche', 'a bedside table'),
                ('una alfombra', 'a rug'),
                ('una cómoda', 'a chest of drawers'),
                ('una silla', 'a chair'),
                ('unas cortinas', 'curtains'),
                ('una puerta', 'a door'),
                ('una ventana', 'a window'),
                ('una lámpara', 'a lamp'),
                ('delante de', 'in front of'),
                ('enfrente de', 'facing'),
                ('detrás de', 'behind'),
                ('encima de', 'on / on top of'),
                ('debajo de', 'under'),
                ('entre', 'between'),
                ('al lado de', 'next to'),
                ('cerca de', 'near to'),
                ('lejos de', 'far from'),
            ]
        }, # a section object
    ]
}

'''
contents of spelling bee
'''
SPELLING_BEE = {
    'title': 'Spelling Bee',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections':[
        {
            'title': 'Stage 1',
            'exercises': [
                ('bienvenido', 'welcome'),
                ('y', 'and'),
                ('pero', 'but'),
                ('con', 'with'),
                ('sin', 'without'),
                ('para', 'in order to'),
                ('si', 'if'),
                ('primero', 'first'),
                ('segundo', 'second'),
                ('tercero', 'third'),
                ('un hermano', 'a brother'),
                ('una hermana', 'a sister'),
                ('grande', 'big'),
                ('pequeño', 'small'),
                ('hay', 'there is/are'),
                ('ayer', 'yesterday'),
                ('hoy', 'today'),
                ('mañana', 'tomorrow'),
                ('porque', 'because'),
                ('¿quién?', 'who?'),
                ('¿dónde?', 'where?'),
                ('¿cómo?', 'how?'),
                ('¿por qué?', 'why?'),
                ('¿qué?', 'what?'),
                ('¿cuánto?', 'how much/many?')
            ]
        },  # a section object
        {
            'title': 'Stage 2',
            'exercises': [
                ('lunes', 'Monday'),
                ('martes', 'Tuesday'),
                ('miércoles', 'Wednesday'),
                ('jueves', 'Thursday'),
                ('viernes', 'Friday'),
                ('sábado', 'Saturday'),
                ('domingo', 'Sunday'),
                ('durante', 'during'),
                ('antes', 'before'),
                ('después', 'after'),
                ('ahora', 'now'),
                ('la mañana', 'the morning'),
                ('la tarde', 'the afternoon / the evening'),
                ('la noche', 'the night'),
                ('un día', 'a day'),
                ('una semana', 'a week'),
                ('un mes', 'a month'),
                ('un año', 'a year'),
                ('temprano', 'early'),
                ('tarde', 'late'),
                ('nunca', 'never'),
                ('a veces', 'sometimes'),
                ('a menudo', 'often'),
                ('luego', 'next')
            ]
        },  # a section object
        {
            'title': 'Stage 3',
            'exercises': [
                ('enero', 'January'),
                ('febrero', 'February'), 
                ('marzo', 'March'), 
                ('abril', 'April'), 
                ('mayo', 'May'), 
                ('junio', 'June'), 
                ('julio', 'July'), 
                ('agosto', 'August'), 
                ('septiembre', 'September'), 
                ('octubre', 'October'), 
                ('noviembre', 'November'), 
                ('diciembre', 'December'), 
                ('muy', 'very'), 
                ('bastante', 'quite'),
                ('mucho', 'a lot'),
                ('poco', 'a little'),
                ('interesante', 'interesting'),
                ('rápido/a', 'fast'),
                ('divertido/a', 'fun'),
                ('fantástico/a', 'brilliant'),
                ('fatal', 'rubbish/awful'),
                ('agradable', 'pleasant'),
                ('difícil', 'difficult'),
                ('fácil', 'easy'),
                ('pues', 'then')
            ]
        }, # a section object
        {
            'title': 'Stage 4',
            'exercises': [
                ('tener', 'to have'),
                ('ayudar', 'to help'),
                ('ir', 'to go'),
                ('jugar', 'to play'),
                ('hacer', 'to to / to make'),
                ('llegar', 'to arrive'),
                ('odiar', 'to hate'),
                ('ganar', 'to win'),
                ('perder', 'to lose'),
                ('nadar', 'to swim'),
                ('trabajar', 'to work'),
                ('beber', 'to drink'),
                ('comer', 'to eat'),
                ('llamar', 'to call'),
                ('un ordenador', 'a computer'),
                ('un móvil', 'a mobile phone'),
                ('un libro', 'a book'),
                ('un bolígrafo', 'a pen'),
                ('entrada', 'entrance'),
                ('salida', 'exit'),
                ('quizás', 'maybe'),
                ('sobre', 'on'),
                ('debajo', 'under'),
                ('delante', 'in front'),
                ('detrás', 'behind')
            ]
        }, # a section object
    ]
}


'''
contents from tutor
'''
TUTOR = {
    'title': 'Tutor',
    'user': 'Zhenglin',
    'template': 'table',
    'subject': 'spanish',
    'sections':[
        {
            'title': 'Vocabulary',
            'exercises': [
                ('alumnos', 'students'),
                ('estuche', 'pencil case'),
                ('sacapuntas', 'sharpener'),
                ('regla', 'ruler'),
                ('pelota', 'ball'),
                ('ventana', 'window'),
                ('dar miedo', 'scare'),
                ('coche', 'car'),
                ('barco', 'boat / ship'),
                ('obra de teatro', 'a play'),
                ('semáforo', 'traffic lights'),
                ('la derecha', 'to the right / the right'),
                ('la izquierda', 'to the left / the left'),
                ('queso', 'cheese'),
                ('cero', 'zero'),
                ('la gente', 'people'),
                ('girar', 'to turn'),
                ('gota', 'drop'),
                ('bolos', 'bowling'),
                ('billar', 'pool'),
                ('tenis', 'tennis'),
                ('fútbol', 'football'),
                ('remo', 'rowing'),
                ('bucear', 'diving'),
                ('patinar', 'rollerskating'),
                ('windsurf', 'windsurfing'),
                ('loro', 'parrot'),
                ('marisco', 'sea food'),
                ('chiringuito', 'restaurant next to beach or sea'),
                ('vistas', 'sight'),
                ('creer', 'to believe'),
                ('maravillosa', 'wonderful'),
                ('dinero de bolsillo', 'pocket money'),
                ('sobre', 'about'),
                ('dar', 'to give'),
                ('eso', 'that'),
                ('entonces', 'then'),
                ('paso la aspiradora', 'to voccum'),
                ('mala', 'bad'),
                ('suerte', 'luck'),
                ('gastar', 'to spend'),
                ('suelen', 'usually'),
                ('películas', 'movies'),
                ('algún', 'some'),
                ('ver', 'to watch'),
                ('tocar', '(instead of jugar) to play (instruments)'),
                ('país', 'country'),
                ('Francia', 'France'),
                ('cálidos', 'warm (weather)'),
                ('atracciones', 'rides (in a theme park)'),
                ('¿Qué hora es? / ¿Tines hora? / ¿Me puede decir la hora?', 'What is the time?'),
                ('madrugada', 'early morning, dawn'),
                ('Noruega', 'Norway'),
                ('Reino Unido', 'U.K.'),
                ('abren', 'open'),
                ('cierran', 'closed'),
                ('levantarse', 'to wake up'),
                ('navegar', 'to sail, to surf'),
                ('barrio', 'neighbourhood'),
                ('tomar', 'to drink'),
                ('basura', 'junk food'),
                ('duele', 'ache'),
                ('doler', 'to hurt, have pain'),
                ('encuentra', 'found, located'),
                ('comunicación', 'communication'),
                ('abogada', 'lawyer'),
                ('despacho', 'office'),
                ('empresariales', 'business'),
                ('la profesión', 'profession, job'),
                ('médico', 'doctor'),
                ('¿Que haces?', 'What do you do?'),
                ('¿A qué te dedicas? / ¿En qué trabajas?', 'What\'s your job?'),
            ]
        }
    ]
}
